export default {
  共工空间: 'Gonggong Space',
  消息: 'Messages',
  通知: 'Notifications',
  管理后台: 'Admin console',
  新建群: 'New group',
  '搜索消息、文件、运行': 'Search messages, files and runs',
  搜索: 'Search',
  '连接已断开，正在重连…': 'Disconnected. Reconnecting…',
  会话列表: 'Conversations',
  调整侧栏宽度: 'Resize sidebar',
  侧栏: 'Sidebar',
  收起聊天: 'Collapse chat',
  展开聊天: 'Expand chat',
  调整聊天栏宽度: 'Resize chat',
  'Bot 不存在或已删除': "This Bot doesn't exist or was deleted",
  加载中: 'Loading',
  加载失败: 'Failed to load',
  '无法获取群列表，请检查网络后重试。': "Couldn't load groups. Check your network and try again.",
  重试: 'Retry',
  群不存在或你已不在群内: "This group doesn't exist or you're no longer a member",
  选择一个群或私聊开始: 'Pick a group or direct message to start',
  '在左侧选择会话；@ Bot 即可让团队成员机器上的 Claude Code / Codex 开始工作。':
    "Pick a conversation on the left; @ a Bot to put Claude Code / Codex to work on a teammate's machine.",
  加载工作区失败: 'Failed to load workspace',
  无法连接服务器: "Can't reach the server",
  '请检查网络或服务器状态后重试。': 'Check your network or the server status and try again.',
  '正在连接…': 'Connecting…',
  分区模式: 'Partition mode',
  强制同步: 'Force sync',
  已连接: 'Connected',
  '连接中…': 'Connecting…',
  '已断开 · 重连中': 'Disconnected · reconnecting',
  '仅你和你的 Bot': 'Just you and your Bots',
  '{n} 人 · {mode}': '{n} {n:member|members} · {mode}',
  绑定机器: 'Bind machine',
  '在机器上安装共工空间客户端，打开接入链接关联账号':
    'Install the Gonggong Space client on a machine and open the connect link to link your account',
  '新建 Bot': 'New Bot',
  '选择机器上的 Claude Code 或 Codex': 'Pick Claude Code or Codex on a machine',
  '建群并 @ Bot': 'Create a group and @ a Bot',
  '拉上同事、绑定仓库，分配任务': 'Invite teammates, bind repos, hand out tasks',
  开始使用: 'Get started',
  展开会话列表: 'Expand conversations',
  '{n} 个 Bot 在线': '{n} {n:Bot|Bots} online',
  '{n} 台机器在线': '{n} {n:machine|machines} online',
  '群#nav': 'Groups',
  还没有加入任何群: "You haven't joined any groups yet",
  '私聊#nav': 'Direct messages',
  新建私聊: 'New direct message',
  还没有私聊: 'No direct messages yet',
  '我的 Bot': 'My Bots',
  '新建 Bot…': 'New Bot…',
  '还没有 Bot': 'No Bots yet',
  我的机器: 'My machines',
  绑定新机器: 'Bind new machine',
  '{n} 个 Bot': '{n} {n:Bot|Bots}',
  在线: 'Online',
  离线: 'Offline',
  还没有绑定机器: 'No machines bound yet',
  确认: 'Confirm',
  '在你的机器上安装共工空间客户端并打开接入链接，Bot 就在这台机器上运行。':
    'Install the Gonggong Space client on your machine and open the connect link; your Bots run on that machine.',
  '选择机器上的 Claude Code 或 Codex，给它起个好认的名字。':
    'Pick Claude Code or Codex on a machine and give it a memorable name.',
  '拉上同事、绑定仓库，在群里 @ 你的 Bot 分配任务。':
    'Invite teammates, bind repos, and @ your Bot in the group to hand out tasks.',
  '欢迎来到共工空间，{name}': 'Welcome to Gonggong Space, {name}',
  '三步让你的第一个 Bot 开工。也可以等同事把你拉进群，直接参与协作。':
    'Three steps to get your first Bot working. Or wait for a teammate to add you to a group and jump right in.',
} satisfies Record<string, string>
