export default {
  '消息免打扰#muted': 'Muted',
  '仅你和你的 Bot · ': 'Only you and your Bot · ',
  '{owner} 共享的 Bot · ': 'Bot shared by {owner} · ',
  'Bot 已取消共享或已删除，只能查看历史消息。':
    'The Bot is no longer shared or was deleted; only the history can be read.',
  '{n} 人 · {bots} Bot · ': '{n} {n:member|members} · {bots} {bots:Bot|Bots} · ',
  '{n} 人 · ': '{n} {n:member|members} · ',
  '未绑定仓库 · Bot 使用本机目录': 'No repo · the Bot uses a local folder',
  '未绑定仓库 · 各 Bot 使用本机目录': 'No repo · each Bot uses a local folder',
  '群成员：{n} 人，{bots} 个 Bot': 'Group members: {n} {n:person|people}, {bots} {bots:Bot|Bots}',
  '群成员：{n} 人': 'Group members: {n} {n:person|people}',
  工作台: 'Workbench',
  '工作台 · 还没有打开的标签页': 'Workbench · no tabs open yet',
  群设置: 'Group settings',
  添加附件: 'Add attachments',
  松开以添加附件: 'Drop to attach',
  '随下一条消息发送给群里的 Bot': "Sent to the group's Bots with your next message",
  加载更早消息失败: "Couldn't load earlier messages",
  重试: 'Retry',
  消息加载失败: "Couldn't load messages",
  '请检查网络后重试。': 'Check your network and try again.',
  加载中: 'Loading',
  还没有消息: 'No messages yet',
  '@ 一个 Bot 让它开始工作，不 @ 的消息会作为上下文补送。':
    '@ a Bot to put it to work. Messages without an @ are passed along as context.',
  '{n} 条新消息': '{n} new {n:message|messages}',
  收起: 'Collapse',
  展开全文: 'Show all',
  文件夹: 'Folder',
  '该文件不在你的工作区，可能需要拉取': "This file isn't in your workspace; you may need to pull",
  未提交: 'Uncommitted',
  成员: 'Members',
  '成员 / Bot': 'Members / Bots',
  文件: 'Files',
  '来源：{source}': 'Source: {source}',
  系统命令: 'System commands',
  'AGENT 命令': 'Agent commands',
  'ACP 上报': 'Reported via ACP',
  '团队 Skill': 'Team skills',
  配置中心: 'Configuration',
  '/ 命令': '/ commands',
  '@ 候选': '@ suggestions',
  '{bot} 的上下文': "{bot}'s context",
  '{bot} 上下文 {detail}': '{bot} context {detail}',
  '上下文 {detail}': 'Context {detail}',
  上下文占用: 'Context usage',
  上下文: 'Context',
  '即将用满，Agent 会自动压缩。': 'Almost full; the agent will compact it automatically. ',
  '压缩会把此前的对话总结后保留；开新对话则不再带上此前的对话。':
    'Compacting keeps a summary of the conversation so far; a new conversation leaves it behind.',
  开新对话: 'New conversation',
  压缩上下文: 'Compact context',
  托管: 'Managed',
  本机目录: 'Local folder',
  待创建: 'Pending',
  'clone 中…': 'Cloning…',
  工作区创建失败: 'Workspace setup failed',
  '落后 {n} 个提交': '{n} {n:commit|commits} behind',
  '领先 {n} 个提交': '{n} {n:commit|commits} ahead',
  '查看 {name} 的改动': "View {name}'s changes",
  改动: 'Changes',
  '浏览 {name} 的文件': "Browse {name}'s files",
  复制失败: 'Copy failed',
  '超过 24 小时，无法撤回': "Messages older than 24 hours can't be recalled",
  编辑消息: 'Edit message',
  'Enter 保存 · Esc 取消': 'Enter to save · Esc to cancel',
  '删除消息？': 'Delete message?',
  取消: 'Cancel',
  删除: 'Delete',
  '删除后仅对你隐藏，其他成员仍可见': 'It will be hidden only for you; other members still see it',
  复制链接: 'Copy link',
  撤回: 'Recall',
  表情回应: 'Reactions',
  引用回复: 'Quote reply',
  复制: 'Copy',
  已复制: 'Copied',
  链接已复制: 'Link copied',
  消息操作: 'Message actions',
  更多: 'More',
  '发消息，@ 触发 Bot': 'Message, @ a Bot to start it',
  '输入消息，@ 触发 Bot 或引用文件，/ 查看命令': 'Message, @ a Bot or a file, / for commands',
  '@ 提及': '@ mention',
  附件: 'Attachment',
  图片: 'Image',
  '未 @ 的消息不会触发 Bot，会作为背景补充给下一次任务':
    "Messages without an @ don't start a Bot; they're added as context for its next task",
  '分支 {branch} 不存在': 'Branch {branch} not found',
  '{n} 个 Bot 进群后暂停，主人配置凭据后可重新检查':
    '{n} {n:Bot|Bots} will be paused on joining; owners can recheck after setting up credentials',
  新建私聊: 'New direct message',
  新建群: 'New group',
  '检查中…': 'Checking…',
  创建: 'Create',
  名称: 'Name',
  '如：退款 v2 迁移': 'e.g. Refunds v2 migration',
  '移除 {name}': 'Remove {name}',
  '添加 Bot…': 'Add Bot…',
  '成员 · {n}': 'Members · {n}',
  '（Bot 主人自动加入）': ' (Bot owners join automatically)',
  群管理员: 'Group admin',
  'Bot 主人，自动加入': 'Bot owner, joins automatically',
  'Bot 主人': 'Bot owner',
  添加成员: 'Add member',
  '{name} 本会话使用 {session}；已切换为 {effective}，开启新会话后生效':
    '{name} uses {session} in this session; switched to {effective}, which takes effect in a new session',
  开启新会话: 'Start new session',
  '只有 Bot 主人或群管理员可以切换': 'Only the Bot owner or a group admin can change this',
  '{name} 的模型与推理强度': "{name}'s model and reasoning effort",
  '正在读取可选模型…': 'Loading available models…',
  机器尚未上报可选模型: "The machine hasn't reported its models yet",
  模型: 'Model',
  推理强度: 'Reasoning effort',
  设为本群默认: 'Set as group default',
  仅本条: 'This message only',
  排队中: 'Queued',
  离线等待: 'Waiting for machine',
  无权触发: 'Not allowed',
  运行中: 'Running',
  等待审批: 'Awaiting approval',
  等待回答: 'Awaiting answer',
  已中断: 'Interrupted',
  已作废: 'Void',
  '改动 {n} 个文件': '{n} {n:file|files} changed',
  '子 agent {n} 个，{running} 个运行中': '{n} {n:subagent|subagents}, {running} running',
  '子 agent {n} 个': '{n} {n:subagent|subagents}',
  '后台任务 {n} 个运行中': '{n} background {n:task|tasks} running',
  '耗时 {time}': 'Took {time}',
  '接力 {hop}/{max}': 'Relay {hop}/{max}',
  '扇出 · {n} 个 Bot 并行': 'Fan-out · {n} {n:Bot|Bots} in parallel',
  '{label}：{bots}': '{label}: {bots}',
  '、': ', ',
  '剩余 {time}': '{time} left',
  机器离线: 'Machine offline',
  '会话恢复失败，已开新会话并补送最近 50 条群消息':
    "Couldn't resume the session; started a new one with the last 50 group messages",
  已按要求开启新会话: 'Started a new session as requested',
  本轮因配置变更开启新会话: 'New session for this turn after a config change',
  '原供应商已删除，已开启新会话': 'The previous provider was deleted; started a new session',
  今天: 'Today',
  昨天: 'Yesterday',
  用量未上报: 'Usage not reported',
  '{n} 条系统事件 · {last}': '{n} system {n:event|events} · {last}',
  你撤回了一条消息: 'You recalled a message',
  '{name} 撤回了一条消息': '{name} recalled a message',
  '引用回复等同 @ 该 Bot': 'Quoting a reply @-mentions the Bot',
  '还有 {n} 个文件，查看完整改动': '{n} more {n:file|files}; view all changes',
  '让 {name} 处理': 'Hand to {name}',
  '{name} 的运行卡片': "{name}'s run card",
  查看过程: 'View process',
  '{agent} · {name} 触发': '{agent} · started by {name}',
  展开: 'Expand',
  网络或证书问题: 'network or certificate problem',
  连接超时: 'connection timed out',
  '正在让 {name} 的机器重新 clone…': "Asking {name}'s machine to clone again…",
  '{name} 已暂停：所在机器无法访问仓库（{why}），在这台机器上配置 git 凭据后重新检查':
    "{name} is paused: its machine can't reach the repo ({why}). Set up git credentials on that machine, then recheck",
  '{name} 已暂停：所在机器无法访问仓库（{why}），等待 {owner} 处理':
    "{name} is paused: its machine can't reach the repo ({why}). Waiting for {owner}",
  重新检查: 'Recheck',
  '{n} 个 Bot 还没有工作区，此前 @ 它们不会执行':
    "{n} Bots have no workspace yet; @-mentions won't run them until then",
  '绑定 {name}': 'Bind {name}',
  '为 {name} 选择工作区后才能开始工作，此前 @ 它不会执行':
    "Choose a workspace for {name} before it can work; @-mentions won't run it until then",
  '等待 {owner} 为 {name} 绑定工作区': 'Waiting for {owner} to bind a workspace for {name}',
  绑定工作区: 'Bind workspace',
  '+{n} 个子仓库有改动': '+{n} {n:sub-repo|sub-repos} changed',
  '{n} 个子仓库': '{n} {n:sub-repo|sub-repos}',
  '{name} 的子仓库': "{name}'s sub-repos",
  游离: 'Detached',
} satisfies Record<string, string>
