export default {
  外观: 'Appearance',
  'Git 与仓库': 'Git & repos',
  账户: 'Account',
  浅色: 'Light',
  深色: 'Dark',
  跟随系统: 'System',
  清透: 'Clear',
  标准: 'Standard',
  着色: 'Tinted',
  按仓库地址: 'Match repo URL',
  '优先 SSH': 'Prefer SSH',
  '优先 HTTPS': 'Prefer HTTPS',
  设置: 'Settings',
  语言: 'Language',
  主题: 'Theme',
  玻璃效果: 'Glass effect',
  已连接的账号: 'Connected accounts',
  需要重新连接: 'Needs reconnecting',
  断开: 'Disconnect',
  '添加账号…': 'Add account…',
  克隆: 'Clone',
  协议偏好: 'Protocol preference',
  '我的 Bot 克隆或检查仓库时优先尝试的协议': 'Protocol my Bots try first when cloning or checking a repo',
  共工空间: 'Gonggong Space',
  '共工空间：列出我的仓库和分支（只读）': 'Gonggong Space: list my repos and branches (read-only)',
  '名称、90 天有效期、Contents 只读': 'name, 90-day expiry, Contents read-only',
  'Repository access 选「All repositories」；要列出组织仓库，Resource owner 选对应组织':
    'Under Repository access choose "All repositories"; to list organization repos, set Resource owner to that organization',
  '点「Generate token」，复制以 github_pat_ 开头的 Token，粘贴到下方':
    'Click "Generate token", copy the token starting with github_pat_ and paste it below',
  '名称、read_api 权限': 'name, read_api scope',
  '按需设置过期时间，点「Create token」': 'Set an expiry if needed, then click "Create token"',
  '复制以 glpat- 开头的 Token，粘贴到下方': 'Copy the token starting with glpat- and paste it below',
  '如何获取 Token': 'How to get a token',
  '打开已预填（{fields}）的创建页': 'Open the prefilled creation page ({fields})',
  先填写实例地址: 'Enter the instance URL first',
  '在 {provider} 创建 Token': 'Create token on {provider}',
  'Token 只用于列出仓库和分支，加密保存在服务器，不用于 clone。':
    'The token is only used to list repos and branches, is stored encrypted on the server, and is never used to clone.',
  '连接失败，请重试': 'Connection failed, please try again',
  '添加 Git 账号': 'Add Git account',
  取消: 'Cancel',
  '验证中…': 'Verifying…',
  连接: 'Connect',
  类型: 'Type',
  实例地址: 'Instance URL',
  显示名: 'Display name',
  '修改显示名…': 'Change display name…',
  密码: 'Password',
  '修改密码…': 'Change password…',
  '保存失败，请重试': 'Save failed, please try again',
  修改显示名: 'Change display name',
  保存: 'Save',
  在群成员与消息里显示: 'Shown in group members and messages',
  邮箱: 'Email',
  未设置: 'Not set',
  '修改邮箱…': 'Change email…',
  修改邮箱: 'Change email',
  留空即清除: 'Leave empty to clear',
  头像: 'Avatar',
  上传头像: 'Upload avatar',
  '上传头像…': 'Upload avatar…',
  使用飞书头像: 'Use Feishu avatar',
  移除头像: 'Remove avatar',
  '头像仅支持 PNG、JPEG、WebP 或 GIF 图片': 'Avatars must be PNG, JPEG, WebP or GIF images',
  '头像不能超过 {maxMb} MB': 'An avatar cannot exceed {maxMb} MB',
} satisfies Record<string, string>
