export default {
  '默认（{name}）': 'Default ({name})',
  默认: 'Default',
  模型: 'Model',
  '跟随默认 · 机器上报可选模型后可设置': 'Follows default · Available once the machine reports its models',
  '群内可临时切换，发消息时也可单条指定': 'Can be switched in a group, or set per message',
  推理强度: 'Reasoning effort',
  每次询问: 'Ask every time',
  白名单自动: 'Auto for allowlist',
  全部自动: 'Auto for all',
  命令审批: 'Command approval',
  '只有 Bot 主人能修改命令审批': 'Only the Bot owner can change command approval',
  '、': ', ',
  命令白名单: 'Command allowlist',
  输入命令前缀后按: 'Type a command prefix and press',
  '添加。以这些前缀开头的命令自动批准；用 &&、;、| 连接时每一段都要在白名单内（cat、ls、git status 等只读命令除外），写文件的重定向或 $( ) 仍需你审批。':
    'to add it. Commands starting with these prefixes are approved automatically; when chained with &&, ; or |, every part must be on the allowlist (read-only commands like cat, ls, git status excepted). Redirects that write files and $( ) still need your approval.',
  '命令前缀，如 go build': 'Command prefix, e.g. go build',
  'Bot 详情': 'Bot details',
  托管工作区: 'Managed workspace',
  '空闲，在群里 @ 它即可开工': 'Idle · @ it in a group to start work',
  '{machine} 离线，被 @ 的请求会等待机器上线': '{machine} is offline; requests wait until it comes online',
  '{ago}开始': 'Started {ago}',
  '还没有加入任何群，把它拉进群后即可 @ 它': 'Not in any group yet. Add it to a group, then @ it',
  工作位置: 'Where it works',
  私聊: 'Direct',
  尚未运行: 'Not run yet',
  工作区未就绪: 'Workspace not ready',
  'token 合计': 'Total tokens',
  运行轮次: 'Runs',
  未上报轮次: 'Unreported runs',
  所在群: 'Groups',
  谁用了: 'Used by',
  按群: 'By group',
  权限档位: 'Permission tier',
  触发范围: 'Who can trigger',
  并发上限: 'Concurrency limit',
  '{n} 个群并行': '{n} {n:group|groups} in parallel',
  默认工作区: 'Default workspace',
  未设置: 'Not set',
  'Bot 概况': 'Bot overview',
  '编辑 Bot': 'Edit Bot',
  编辑: 'Edit',
  详情: 'Details',
  '{n} 个群': '{n} {n:group|groups}',
  '近 {n} 天用量': 'Usage in the last {n} days',
  配置: 'Configuration',
  '只有 Bot 主人可以设置其供应商': 'Only the Bot owner can set its provider',
  '只能在自己的机器上设置 Bot 的供应商': "A Bot's provider can only be set on your own machine",
  '机器离线，上线后才能设置': 'The machine is offline; set this once it is online',
  '请先升级该机器的 daemon': "Upgrade this machine's daemon first",
  '{name} 的供应商已切换，新会话生效': "{name}'s provider switched; applies to new sessions",
  '继承机器（当前：{name}）': 'Inherit from machine (currently: {name})',
  供应商: 'Provider',
  '只保存在 Bot 所在的机器上；进行中的会话开启新会话后才切换':
    "Stored only on the Bot's machine; ongoing sessions switch once a new session starts",
  '读取中…': 'Loading…',
  完全访问档位只允许指定名单触发: 'The Full access tier only allows a specified list to trigger',
  '等待 {owner} 确认': 'Waiting for {owner} to confirm',
  '{creator} 为{owner}创建并绑定到 {machine}。机器主人在 Web 通知或 Bot 详情中确认后才能被触发。':
    '{creator} created it for {owner} and bound it to {machine}. It can be triggered once the machine owner confirms in web notifications or Bot details.',
  待绑定: 'Pending binding',
  '{owner} 绑定第一台机器并上报 {agent} 后自动绑定，无需再操作；此前不能被触发。':
    'Binds automatically once {owner} binds a first machine that reports {agent}; no further action needed. It cannot be triggered until then.',
  '{agent} 未安装': '{agent} not installed',
  '{machine} 未上报 {agent}。在该机器安装并重新检测后自动可用。':
    '{machine} has not reported {agent}. Install it on that machine and re-detect; it becomes available automatically.',
  'agent 版本低于适配器要求': 'Agent version is below the adapter requirement',
  '{machine} 上的 {cli} 低于 ACP 适配器要求的 {min}，可能无法正常运行，请升级该 CLI。':
    '{cli} on {machine} is older than {min} required by the ACP adapter and may not work properly. Please upgrade the CLI.',
  确认: 'Confirm',
  '{usage} · {n} 轮': '{usage} · {n} {n:run|runs}',
  用量未上报: 'Usage not reported',
  默认工作区路径: 'Default workspace path',
  '{name} 已保存 · 下一次新开会话时生效': '{name} saved · Applies from the next new session',
  角色: 'Role',
  系统提示词: 'System prompt',
  '作为 Bot 的角色说明和群内简介，群内可再补充；下一次新开会话时生效':
    "The Bot's role description and group intro; groups can add to it. Applies from the next new session",
  '未绑定仓库的群和私聊中自动使用；绑定仓库的群默认托管克隆':
    'Used automatically in groups without a repo and in direct chats; groups with a repo use a managed clone by default',
  '选择…': 'Choose…',
  清除: 'Clear',
  触发名单: 'Trigger list',
  输入成员姓名: 'Enter member names',
  默认权限档位: 'Default permission tier',
  '同时运行的轮次，超出的在本机排队': 'Runs at the same time; extra runs queue on the machine',
  '{n} 个': '{n}',
  'agent 版本': 'Agent version',
  '近 7 天用量': 'Usage (last 7 days)',
  '近 7 天无人使用': 'Nobody used it in the last 7 days',
  '删除 Bot': 'Delete Bot',
  保存: 'Save',
  '全部 Bot 的归属、绑定与状态；可为任何成员新建，新建时直接绑定归属人的机器与 agent。':
    "Owner, binding and status of every Bot. Create one for any member; it binds to the owner's machine and agent on creation.",
  '{n} 个 Bot': '{n} {n:Bot|Bots}',
  '新建 Bot…': 'New Bot…',
  '搜索 Bot、归属人或机器': 'Search Bots, owners or machines',
  'Bot 列表': 'Bot list',
  '删除 Bot…': 'Delete Bot…',
  '没有匹配的 Bot': 'No matching Bots',
  归属人: 'Owner',
  绑定: 'Binding',
  状态: 'Status',
  '还没有 Bot': 'No Bots yet',
  'Bot 绑定到成员的机器，在群里被 @ 后开工。':
    "A Bot is bound to a member's machine and starts work when @-mentioned in a group.",
  '要删除 {name} 吗？': 'Delete {name}?',
  '删除后不可恢复，群消息与运行记录保留。': 'This cannot be undone. Group messages and run history are kept.',
  '从所在的 {n} 个群移除': 'Removed from {n} {n:group|groups}',
  当前不在任何群: 'Not in any group',
  删除: 'Delete',
  '已删除 {name}': 'Deleted {name}',
  '{owner}的 {agent}': "{owner}'s {agent}",
  '新建 Bot': 'New Bot',
  创建时直接绑定到归属人的机器: "Binds to the owner's machine on creation",
  取消: 'Cancel',
  创建: 'Create',
  '已发送确认通知给 {name}': 'Confirmation request sent to {name}',
  '在要运行 Bot 的机器上用共工空间客户端打开接入链接，绑定并上报 {agent} 后自动可用。':
    'Open the connect link in the Gonggong Space client on the machine that will run the Bot. It becomes available once bound and {agent} is reported.',
  '{owner} 绑定第一台机器并上报 {agent} 后自动可用。':
    'Available once {owner} binds a first machine that reports {agent}.',
  '机器 {machine} 当前离线，打开该机器上的共工空间客户端后即可使用':
    'Machine {machine} is offline. Open the Gonggong Space client on it to start using the Bot',
  '已就绪，可以在群里 @ 它了': 'Ready. You can @ it in a group now',
  '{name} 已创建': '{name} created',
  完成: 'Done',
  绑定后暂不可用: 'Unavailable after binding',
  创建后立即可用: 'Available right after creation',
  '绑定到 {machine} · {agent} {version}，可直接拉入群触发。':
    'Binds to {machine} · {agent} {version}; add it to a group to trigger it.',
  '绑定到 {machine} · {agent} {version}，可直接拉入群触发。机器当前离线，上线后开始执行。':
    'Binds to {machine} · {agent} {version}; add it to a group to trigger it. The machine is offline; runs start once it is online.',
  '已绑定到 {machine}。机器上的操作由主人负责，{owner} 在 Web 通知中一键确认后即可触发。':
    'Bound to {machine}. The owner is responsible for actions on the machine; it can be triggered once {owner} confirms in web notifications.',
  '默认工作区未设置：{error}': 'Default workspace not set: {error}',
  创建并绑定: 'Create and bind',
  创建并发送确认: 'Create and request confirmation',
  '系统管理员可为任何人创建；成员本人只能为自己创建。':
    'System admins can create Bots for anyone; members can only create their own.',
  '{name}（我）': '{name} (me)',
  '{name} · {n} 台机器': '{name} · {n} {n:machine|machines}',
  执行机器: 'Machine',
  在线: 'Online',
  离线: 'Offline',
  '{owner} 还没有绑定机器。Bot 会以「待绑定」创建，可先选 agent 种类。':
    '{owner} has no bound machine yet. The Bot will be created as "Pending binding"; you can pick the agent now.',
  已安装: 'Installed',
  未安装: 'Not installed',
  名称: 'Name',
  '同时作为群内简介。': 'Also used as its group intro.',
  '后端接口开发，只改 server/ 目录': 'Backend API development; only edits server/',
  '可选；未绑定仓库的群和私聊中自动使用，绑定仓库的群默认托管克隆。':
    'Optional. Used automatically in groups without a repo and in direct chats; groups with a repo use a managed clone by default.',
  '选择目录…': 'Choose folder…',
  共字君: 'Gong',
  默认角色: 'Default role',
  '品牌吉祥物，什么活都肯接，把大家托举在一起':
    'The brand mascot: takes on any job and holds everyone up together',
  '{name}：{line}': '{name}: {line}',
  已绑定: 'Bound',
  待确认: 'Pending confirmation',
  在线空闲: 'Online, idle',
  运行中: 'Running',
  'agent 缺失': 'Agent missing',
  不可触发: 'Cannot be triggered',
  '{name} 已确认': '{name} confirmed',
  任何群成员: 'Any group member',
  指定名单: 'Specified list',
  仅本人: 'Owner only',
  '看着在发呆，其实在想第二层。问题没说清楚，一行代码都不写。':
    "Looks like it's daydreaming, but it's thinking one level deeper. Won't write a line until the problem is clear.",
  慢想: 'Ponder',
  '深思 × 逆向 × 守边界': 'Deep × Contrarian × Principled',
  '嘴毒是因为对代码有洁癖。空谈免谈，只认跑得起来的实现。':
    'Sharp-tongued because it is fussy about code. No hot air; only working code counts.',
  铁码: 'Ironcode',
  '毒舌 × 洁癖 × 实干': 'Blunt × Meticulous × Hands-on',
  '一进心流就戴上耳机屏蔽世界；先测量，只抠真正关键的 3%。':
    'Puts on headphones and shuts out the world in flow; measures first and tunes only the critical 3%.',
  闭关: 'Hermit',
  '沉默 × 狂热 × 精算': 'Quiet × Obsessive × Precise',
  '红了就修，绿了就走；对复杂度零容忍，笑着删功能。':
    'Red? Fix it. Green? Move on. Zero tolerance for complexity; cuts features with a smile.',
  小步: 'Baby Steps',
  '乐天 × 务实 × 敢割舍': 'Upbeat × Pragmatic × Ruthless cutter',
  '说话轻声细语，对粗糙零容忍；每个像素都要讲得出理由。':
    'Soft-spoken with zero tolerance for rough edges; every pixel needs a reason.',
  留白: 'Whitespace',
  '温柔 × 偏执 × 克制': 'Gentle × Perfectionist × Restrained',
  '对诱惑说不，对用户说是；发现方向错了，当场叫停。':
    'Says no to temptation and yes to users; stops on the spot when the direction is wrong.',
  说不: 'Nope',
  '果断 × 本分 × 聚焦': 'Decisive × Dutiful × Focused',
  '不听故事只看账：用户价值 = 新体验 − 旧体验 − 替换成本。':
    'No stories, just numbers: user value = new experience − old experience − switching cost.',
  算盘: 'Abacus',
  '冷静 × 理性 × 算账': 'Calm × Rational × Counts the cost',
  '总在问「它会怎么坏」——就是为了让它永远不坏。': 'Always asks "how will it break?" so that it never does.',
  反推: 'Backtrack',
  '悲观 × 缜密 × 守护': 'Pessimistic × Thorough × Protective',
  '默认已经被攻破，却从不制造恐慌；风险是连续的，不是非黑即白。':
    'Assumes a breach already happened but never spreads panic; risk is a spectrum, not black and white.',
  哨兵: 'Sentinel',
  '警觉 × 冷静 × 讲流程': 'Alert × Calm × By the book',
  '嘴上冷笑话，骨子里抗造；每次事故都让系统更强一点。':
    'Deadpan jokes, tough to the core; every incident makes the system a bit stronger.',
  抗摔: 'Tumbler',
  '冷幽默 × 反脆弱 × 少即是多': 'Dry humor × Antifragile × Less is more',
  '方向寸步不让，路径随时可绕；可逆的决定当场拍板。':
    'Never budges on direction, happy to reroute; makes reversible decisions on the spot.',
  灰度: 'Grayscale',
  '外柔内刚 × 果断 × 放权': 'Soft outside, firm inside × Decisive × Delegates',
  '把问题摊开讲，是为了让人成长；每个里程碑都要复盘。':
    'Lays problems out in the open to help people grow; reviews every milestone.',
  复盘: 'Retro',
  '直率 × 暖心 × 透明': 'Candid × Warm × Transparent',
} satisfies Record<string, string>
