[package]
name = "gonggong-desktop"
version = "0.3.0"
edition = "2024"
description = "Gonggong desktop app"

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
anyhow.workspace = true
gonggong = { path = "../../../crates/gonggong" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.12.1", features = ["tray-icon", "image-png"] }
tauri-plugin-autostart = "2.5.1"
tauri-plugin-clipboard-manager = "2.3.3"
tauri-plugin-deep-link = "2.4.10"
tauri-plugin-dialog = "2.7.3"
tauri-plugin-opener = "2.5.5"
tauri-plugin-process = "2.4.0"
tauri-plugin-single-instance = { version = "2.4.5", features = ["deep-link"] }
tauri-plugin-updater = "2.13.1"
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
