export default {
  'agent 声明支持图片时以 ACP 图片内容直接发送，同时落盘供按路径读取':
    'Sent as ACP image content when the agent supports images, and saved to disk to read by path',
  '视频不直接发送，agent 按路径读取': "Videos aren't sent directly; the agent reads them by path",
  附件加载失败: "Couldn't load the attachment",
  '来源#from': 'From',
  大小: 'Size',
  位置: 'Location',
  '发送给 Bot': 'Sent to Bot',
  工作树: 'Working tree',
  '已加入 .git/info/exclude，不进 git': 'Listed in .git/info/exclude, kept out of git',
  '{name} 超过 50 MB，未添加': '{name} is over 50 MB and was not added',
  '每条消息最多 {n} 个附件': 'Up to {n} attachments per message',
  '引用 {who}': 'Quoting {who}',
  '等同 @，引用内容一起发送': 'Same as an @; the quote is sent along',
  关闭引用: 'Remove quote',
  '预览 {name}': 'Preview {name}',
  点击放大: 'Click to enlarge',
  '移除 {name}': 'Remove {name}',
  '{n} / {max} · 写入工作区 .gonggong/attachments/，不进 git':
    '{n} / {max} · saved to the workspace under .gonggong/attachments/, kept out of git',
  ' · 图片：agent 支持时同时以 ACP 图片发送':
    ' · images: also sent as ACP images when the agent supports them',
  '：': ': ',
  在工作台查看: 'Open in workbench',
  查看大图: 'View full size',
  下载: 'Download',
  ' · 点击预览': ' · click to preview',
  上传失败: 'Upload failed',
  '上传失败，请检查网络': 'Upload failed; check your network',
  图片: 'Image',
  视频: 'Video',
  文本日志: 'Text log',
  代码: 'Code',
} satisfies Record<string, string>
