export default {
  '按 Bot': 'By Bot',
  按触发人: 'By trigger user',
  按群: 'By group',
  未上报: 'Unreported',
  '{n} 个 Bot': '{n} {n:Bot|Bots}',
  '{n} 位触发人': '{n} trigger {n:user|users}',
  '{n} 个群': '{n} {n:group|groups}',
  触发人: 'Trigger user',
  持平: 'Flat',
  '较前 {n} 天': 'vs. previous {n} days',
  'token 合计': 'Total tokens',
  运行轮次: 'Runs',
  未上报轮次: 'Unreported runs',
  参与统计: 'Counted',
  '{n} 轮': '{n} {n:run|runs}',
  '{m}月{d}日': '{m}/{d}',
  '{n} 轮未上报': '{n} {n:run|runs} unreported',
  '近 {n} 天每日 token：合计 {total}': 'Daily tokens over the last {n} days: {total} total',
  '近 {n} 天每日运行轮次：合计 {total}': 'Daily runs over the last {n} days: {total} total',
  '，峰值 {day} {value}': ', peak {day} {value}',
  每日趋势: 'Daily trend',
  趋势指标: 'Trend metric',
  轮次: 'Runs',
  其他: 'Other',
  'token 分布': 'Token share',
  '合计 {total} tokens': '{total} tokens total',
  'token 分布：{parts}': 'Token share: {parts}',
  '，': ', ',
  'token 分布图例': 'Token share legend',
  用量明细: 'Usage details',
  占比: 'Share',
  '近 30 天没有运行': 'No runs in the last 30 days',
  '近 30 天 · 不做配额限制 · Codex 适配器未上报的轮次计为「未上报」，不计入 token 合计。':
    'Last 30 days · No quotas · Runs the Codex adapter did not report count as "Unreported" and are excluded from token totals.',
  用量: 'Usage',
  '按 Bot、触发人、群汇总 token 用量。': 'Token usage by Bot, trigger user and group.',
  我的用量: 'My usage',
  '我的 Bot 近 30 天用量': 'Usage of my Bots in the last 30 days',
} satisfies Record<string, string>
