export default {
  每天: 'Daily',
  每个工作日: 'Weekdays',
  每周: 'Weekly',
  每月: 'Monthly',
  仅一次: 'Once',
  自定义: 'Custom',
  编辑定时任务: 'Edit scheduled task',
  新建定时任务: 'New scheduled task',
  指令: 'Instructions',
  '如：每日 PR 汇总': 'e.g. Daily PR digest',
  '到点发给 Bot 的完整指令：要做什么、范围和产出':
    'Sent to the Bot when it fires: what to do, the scope and the output',
  '候选 Bot · 到点由第一个可用的执行': 'Candidate Bots · the first available one runs it',
  '上移 {name}': 'Move {name} up',
  '添加 {name}': 'Add {name}',
  '本群的 Bot 都已加入': 'Every Bot in this group is added',
  执行时间: 'Timing',
  频率: 'Frequency',
  星期: 'Weekday',
  '日期（每月第几日）': 'Day of the month',
  执行时刻: 'Time to run',
  'cron 表达式': 'cron expression',
  '分 时 日 月 周（0 = 周日），时区 {tz}': 'minute hour day month weekday (0 = Sunday), time zone {tz}',
  时间: 'Time',
  '接下来：{times}': 'Next: {times}',
  排队中: 'Queued',
  '等待 Bot 上线': 'Waiting for the Bot',
  运行中: 'Running',
  等待审批: 'Awaiting approval',
  等待回答: 'Awaiting answers',
  完成: 'Done',
  中断: 'Interrupted',
  无权触发: 'Not allowed',
  离线作废: 'Expired offline',
  '下次 {at}': 'Next {at}',
  已启用: 'On',
  '已停用：{reason}': 'Off: {reason}',
  已暂停: 'Paused',
  '最近 {at} · {bot} {result}': 'Last {at} · {bot} {result}',
  跳过: 'skipped',
  'Bot 创建': 'By Bot',
  '启用「{name}」': 'Turn on "{name}"',
  '{n} / {max} 个': '{n} / {max}',
  还没有定时任务: 'No scheduled tasks yet',
  '到点由 Bot 自动执行一段指令；也可以直接让 Bot 帮你建，例如「每个工作日 9 点汇总昨天的 PR」。':
    'A Bot runs your instructions on time. You can also ask a Bot to set one up, e.g. "every weekday at 9, sum up yesterday\'s PRs".',
  已删除: 'Deleted',
  启用中: 'On',
  '已停用#off': 'Off',
  暂停: 'Pause',
  恢复: 'Resume',
  确认删除: 'Confirm delete',
  定时任务: 'Scheduled tasks',
  已移出: 'Removed',
}
