export default {
  系统管理员: 'System admin',
  普通成员: 'Member',
  我的用量: 'My usage',
  '设置…': 'Settings…',
  退出登录: 'Log out',
  账户菜单: 'Account menu',
  切换到浅色: 'Switch to light',
  切换到深色: 'Switch to dark',
  王磊: 'Wang Lei',
  '小王的 Claude': "Wang's Claude",
  '登录页的表单校验有问题，帮忙修一下': 'the login form validation is broken, can you fix it?',
  '已修复并提交。': 'Fixed and committed. ',
  '李娜的 Codex': "Li Na's Codex",
  '帮忙 review 一下': 'can you review it?',
  '看过了，逻辑没问题，可以合并。': 'Looks good, the logic is fine. Ready to merge.',
  '读取 LoginPage.tsx': 'Read LoginPage.tsx',
  '编辑 2 处校验逻辑': 'Edit 2 validation checks',
  '运行测试 · 12 项通过': 'Run tests · 12 passed',
  'web-site 重构': 'web-site revamp',
  '3 人 · 2 Bot': '3 people · 2 Bots',
  运行中: 'Running',
  用初始密码登录: 'Log in with the initial password',
  设置自己的密码: 'Set your own password',
  '绑定机器、新建 Bot，开始协作': 'Bind a machine, create a Bot, start collaborating',
  首次登录进度: 'First login progress',
  '人与 Bot 的协作平台': 'Where people and Bots work together',
  '最后一步，': 'One last step:',
  '设置只属于你的密码。': 'set a password of your own.',
  '在群里 @ 一下，': '@ them in the group,',
  '队友的 Bot 就开工。': "and your teammates' Bots get to work.",
  '初始密码由管理员发放；修改后，其他设备上的登录会自动失效。':
    'Your initial password was issued by an admin. Once changed, sessions on other devices are signed out.',
  'Claude Code / Codex 在各自的工作区里干活，接力完成同一个仓库，每一步都看得见。':
    'Claude Code and Codex work in their own workspaces and relay on the same repo, with every step in view.',
  较弱: 'Weak',
  一般: 'Fair',
  较强: 'Strong',
  很强: 'Very strong',
  请输入原密码: 'Enter your current password',
  '新密码至少 {n} 位': 'New password must be at least {n} characters',
  两次输入的新密码不一致: 'The new passwords do not match',
  新密码不能与原密码相同: 'The new password must differ from the current one',
  '至少 {n} 位': 'At least {n} characters',
  与原密码不同: 'Differs from the current password',
  两次输入一致: 'Both entries match',
  新密码: 'New password',
  '强度：{level}': 'Strength: {level}',
  '建议混合字母、数字和符号': 'Mix letters, numbers and symbols',
  确认新密码: 'Confirm new password',
  '保存中…': 'Saving…',
  已更新: 'Updated',
  '密码已更新，欢迎加入共工空间': 'Password updated. Welcome to Gonggong Space',
  修改密码: 'Change password',
  '首次登录需修改管理员设置的初始密码。': 'On first login, change the initial password set by your admin.',
  初始密码: 'Initial password',
  '密码已修改，其他设备上的登录已失效': 'Password changed. Sessions on other devices were signed out',
  '修改后，其他设备上的登录会失效。': 'Sessions on other devices will be signed out.',
  取消: 'Cancel',
  保存新密码: 'Save new password',
  当前密码: 'Current password',
  请输入密码: 'Enter your password',
  请输入账号: 'Enter your account',
  登录: 'Log in',
  '欢迎回来，继续和团队一起干活。': 'Welcome back. Pick up where your team left off.',
  '还没有账号？': 'No account yet? ',
  立即注册: 'Sign up',
  '还没有账号？请联系系统管理员开通': 'No account yet? Ask a system admin to create one',
  账号: 'Account',
  密码: 'Password',
  记住我: 'Remember me',
  '忘记密码？': 'Forgot password?',
  '请联系系统管理员重置密码，用拿到的临时密码登录后再修改。':
    'Ask a system admin to reset it, log in with the temporary password, then change it.',
  '登录中…': 'Logging in…',
  登录成功: 'Logged in',
  '账号需为 2–32 位小写字母、数字或 . _ -': 'Account must be 2–32 lowercase letters, digits or . _ -',
  请填写姓名: 'Enter a name',
  '密码至少 {n} 位': 'Password must be at least {n} characters',
  两次输入的密码不一致: 'The passwords do not match',
  注册: 'Sign up',
  '当前未开放注册，请联系系统管理员创建账号。': 'Sign-up is closed. Ask a system admin to create an account.',
  '注册后即可加入群、绑定机器、创建你的 Bot。': 'Sign up to join groups, bind machines and create your Bots.',
  '已有账号？': 'Already have an account? ',
  去登录: 'Log in',
  '登录用，如 wanglei': 'Used to log in, e.g. wanglei',
  姓名: 'Name',
  群里显示的名字: 'Name shown in groups',
  确认密码: 'Confirm password',
  注册并进入: 'Sign up and continue',
  '注册中…': 'Signing up…',
  注册成功: 'Signed up',
} satisfies Record<string, string>
