export default {
  配置中心: 'Configuration',
  '仓库基线之上叠加服务器全局层与群层，冲突时服务器优先；不修改仓库文件。':
    'Server global and group layers stack on top of the repo baseline; the server wins on conflicts. Repo files are never modified.',
  向群成员提问: 'Ask group members',
  读取聊天记录: 'Read chat history',
  检索聊天记录: 'Search chat history',
  群信息与成员: 'Group info and members',
  查看运行记录: 'View run history',
  提问卡片历史: 'Question card history',
  下载历史附件: 'Download past attachments',
  发布预览: 'Publish preview',
  发布桌面应用预览: 'Publish desktop app preview',
  关闭预览: 'Close preview',
  '交给其他 Bot': 'Hand off to another Bot',
  '、': ', ',
  服务器全局层: 'Server global layer',
  服务器群层: 'Server group layer',
  指令: 'Instructions',
  团队密钥: 'Team secrets',
  保存失败: 'Failed to save',
  '自定义 MCP {n} 个 · 已启用 {enabled} 个': '{n} custom MCP {n:server|servers} · {enabled} enabled',
  配置加载失败: 'Failed to load configuration',
  重试: 'Retry',
  '暂不支持 {type}': '{type} is not supported yet',
  '目前只能配置服务器全局层的 MCP。MCP 的环境变量以明文保存在配置中。':
    'Only MCP in the server global layer can be configured for now. MCP environment variables are stored in plain text.',
  全局层: 'Global',
  未保存: 'Unsaved',
  '删除 {name}': 'Delete {name}',
  '启用 {name}': 'Enable {name}',
  内置: 'Built-in',
  '系统内置 · 始终注入，不受层级影响': 'Built-in · Always injected, regardless of layers',
  '强制相关 Bot 下一轮开新会话': 'Force affected Bots to start a new session next run',
  '勾选后，受影响的 Bot 下一轮会放弃已有会话、按新配置重开，卡片会提示原因；不勾选则已有会话继续使用旧配置。':
    'When checked, affected Bots drop their current session next run and restart with the new configuration, with the reason shown on the card. Otherwise existing sessions keep the old configuration.',
  '添加 MCP…': 'Add MCP…',
  保存: 'Save',
  '合并预览 · 全部 Bot': 'Merged preview · All Bots',
  优先级高: 'Highest priority',
  暂未开放: 'Not available yet',
  中: 'Medium',
  无: 'None',
  'Bot 系统提示词': 'Bot system prompts',
  '各 Bot 在 Bot 页设置': "Set on each Bot's page",
  仓库基线: 'Repo baseline',
  低: 'Low',
  '合并在 daemon 内存完成；MCP 在新建会话时经 ACP 注入不落盘；skill 与指令写入 agent 本地专用文件并加入 .git/info/exclude。内置 gonggong（提问、聊天记录、群信息等）始终注入。':
    "Merging happens in daemon memory. MCP is injected via ACP when a session starts and never written to disk; skills and instructions go to the agent's local-only files, added to .git/info/exclude. The built-in gonggong (questions, chat history, group info, etc.) is always injected.",
  '已保存，全员下一轮新会话生效': "Saved; applies to everyone's next new session",
  '已要求相关 Bot 下一轮开新会话，卡片会提示原因。':
    'Affected Bots will start a new session next run, with the reason shown on the card.',
  '运行中的轮次不受影响；已有会话继续使用旧配置。':
    'Running runs are unaffected; existing sessions keep the old configuration.',
  请填写名称: 'Enter a name',
  '{name} 是系统内置 MCP 的名称': '{name} is the name of the built-in MCP',
  'MCP 名称已存在': 'An MCP with this name already exists',
  请填写命令: 'Enter a command',
  'URL 需以 http:// 或 https:// 开头': 'The URL must start with http:// or https://',
  '添加 MCP': 'Add MCP',
  '保存配置中心后，全员下一轮新会话生效。': "Takes effect in everyone's next new session after saving.",
  取消: 'Cancel',
  添加: 'Add',
  传输方式: 'Transport',
  名称: 'Name',
  命令: 'Command',
  参数: 'Arguments',
  '每行一个。': 'One per line.',
  环境变量: 'Environment variables',
  '{n} 项': '{n} {n:item|items}',
  未设置: 'Not set',
  '每行一个 KEY=VALUE；以明文保存，只在新建会话时经 ACP 注入。':
    'One KEY=VALUE per line. Stored in plain text and injected via ACP only when a session starts.',
  请求头: 'Headers',
  '每行一个 Key: Value；以明文保存，只在新建会话时经 ACP 注入。':
    'One Key: Value per line. Stored in plain text and injected via ACP only when a session starts.',
} satisfies Record<string, string>
