export default {
  配置中心: 'Configuration',
  '仓库基线之上依次叠加平台层、团队层与群层 MCP，同名时下层覆盖上层；不修改仓库文件。':
    'Platform, team and group MCP layers stack on top of the repo baseline; a lower layer replaces a same-named server above it. Repo files are never modified.',
  向群成员提问: 'Ask group members',
  读取聊天记录: 'Read chat history',
  检索聊天记录: 'Search chat history',
  群信息与成员: 'Group info and members',
  查看运行记录: 'View run history',
  提问卡片历史: 'Question card history',
  下载历史附件: 'Download past attachments',
  发布预览: 'Publish preview',
  发布桌面应用预览: 'Publish desktop app preview',
  关闭预览: 'Close preview',
  '交给其他 Bot': 'Hand off to another Bot',
  读取飞书群消息: 'Read Feishu group messages',
  创建定时任务: 'Create scheduled task',
  定时任务列表: 'Scheduled tasks',
  修改定时任务: 'Edit scheduled task',
  删除定时任务: 'Delete scheduled task',
  'Skill 列表': 'Skill list',
  '读取 Skill': 'Read skill',
  '新建 Skill': 'Create skill',
  '修改 Skill': 'Edit skill',
  '删除 Skill': 'Delete skill',
  '启用/停用 Skill': 'Enable/disable skill',
  'Skill 版本历史': 'Skill version history',
  '回滚 Skill': 'Roll back skill',
  '、': ', ',
  平台层: 'Platform',
  团队层: 'Team',
  群层: 'Group',
  群管理员在群设置中配置: 'Set by group admins in group settings',
  团队管理员在团队设置中配置: 'Set by team admins in team settings',
  指令: 'Instructions',
  团队密钥: 'Team secrets',
  保存失败: 'Failed to save',
  '自定义 MCP {n} 个 · 已启用 {enabled} 个': '{n} custom MCP {n:server|servers} · {enabled} enabled',
  配置加载失败: 'Failed to load configuration',
  重试: 'Retry',
  '暂不支持 {type}': '{type} is not supported yet',
  '目前只能配置 MCP 与 Skill。MCP 的环境变量以明文保存在配置中。':
    'Only MCP and skills can be configured for now. MCP environment variables are stored in plain text.',
  未保存: 'Unsaved',
  '删除 {name}': 'Delete {name}',
  '启用 {name}': 'Enable {name}',
  内置: 'Built-in',
  '系统内置 · 始终注入，不受层级影响': 'Built-in · Always injected, regardless of layers',
  '强制相关 Bot 下一轮开新会话': 'Force affected Bots to start a new session next run',
  '勾选后，受影响的 Bot 下一轮会放弃已有会话、按新配置重开，卡片会提示原因；不勾选则已有会话继续使用旧配置。':
    'When checked, affected Bots drop their current session next run and restart with the new configuration, with the reason shown on the card. Otherwise existing sessions keep the old configuration.',
  '添加 MCP…': 'Add MCP…',
  保存: 'Save',
  '合并预览 · 全部 Bot': 'Merged preview · All Bots',
  优先级高: 'Highest priority',
  中: 'Medium',
  无: 'None',
  'Bot 系统提示词': 'Bot system prompts',
  '各 Bot 在 Bot 页设置': "Set on each Bot's page",
  仓库基线: 'Repo baseline',
  低: 'Low',
  '合并在 daemon 内存完成；MCP 在新建会话时经 ACP 注入不落盘；skill 由 daemon 缓存在本机，Claude 以插件注入，Codex 在工作区建软链并加入 .git/info/exclude。内置 gonggong（提问、聊天记录、群信息等）始终注入。':
    'Merging happens in daemon memory. MCP is injected via ACP when a session starts and never written to disk; skills are cached on the machine, injected as a plugin for Claude and symlinked into the workspace for Codex (added to .git/info/exclude). The built-in gonggong (questions, chat history, group info, etc.) is always injected.',
  '已保存，全员下一轮新会话生效': "Saved; applies to everyone's next new session",
  '已要求相关 Bot 下一轮开新会话，卡片会提示原因。':
    'Affected Bots will start a new session next run, with the reason shown on the card.',
  '运行中的轮次不受影响；已有会话继续使用旧配置。':
    'Running runs are unaffected; existing sessions keep the old configuration.',
  请填写名称: 'Enter a name',
  '{name} 是系统内置 MCP 的名称': '{name} is the name of the built-in MCP',
  'MCP 名称已存在': 'An MCP with this name already exists',
  请填写命令: 'Enter a command',
  'URL 需以 http:// 或 https:// 开头': 'The URL must start with http:// or https://',
  '添加 MCP': 'Add MCP',
  '保存后，相关 Bot 下一轮新会话生效。': "Takes effect in affected Bots' next new session after saving.",
  取消: 'Cancel',
  添加: 'Add',
  传输方式: 'Transport',
  名称: 'Name',
  命令: 'Command',
  参数: 'Arguments',
  '每行一个。': 'One per line.',
  环境变量: 'Environment variables',
  '{n} 项': '{n} {n:item|items}',
  未设置: 'Not set',
  '每行一个 KEY=VALUE；以明文保存，只在新建会话时经 ACP 注入。':
    'One KEY=VALUE per line. Stored in plain text and injected via ACP only when a session starts.',
  请求头: 'Headers',
  '每行一个 Key: Value；以明文保存，只在新建会话时经 ACP 注入。':
    'One Key: Value per line. Stored in plain text and injected via ACP only when a session starts.',

  // Skills
  '说明这个 skill 做什么、什么时候使用': 'What this skill does and when to use it',
  '历史版本 {name}': 'Version history of {name}',
  '编辑 {name}': 'Edit {name}',
  '还没有 Skill': 'No skills yet',
  '上传 SKILL.md 所在的文件夹或 zip，保存后相关 Bot 下一轮即可使用。':
    'Upload the folder or zip containing SKILL.md; affected Bots can use it from their next run.',
  '与仓库自带的同名 skill 冲突时跳过团队版，运行卡片会提示。':
    'A team skill named like one in the repo is skipped, with a note on the run card.',
  '添加 Skill…': 'Add Skill…',
  '删除 Skill {name}？': 'Delete skill {name}?',
  '删除后历史版本一并移除，无法恢复。': 'Its version history is removed too. This cannot be undone.',
  '相关 Bot 下一轮起不再加载这个 skill': 'Affected Bots stop loading this skill from their next run',
  '已删除 {name}': 'Deleted {name}',
  导入文件夹: 'Import folder',
  '导入文件夹…': 'Import Folder…',
  '导入 zip': 'Import zip',
  '导入 zip…': 'Import zip…',
  没有读到文件: 'No files found',
  '无法读取：{e}': 'Could not read: {e}',
  '文件已存在：{path}': 'File already exists: {path}',
  '已保存，相关 Bot 下一轮生效': 'Saved; affected Bots pick it up next run',
  '编辑 Skill {name}': 'Edit Skill {name}',
  '添加 Skill': 'Add Skill',
  '名称与描述取自 SKILL.md 开头的 frontmatter；每次保存生成一个新版本。':
    'Name and description come from the frontmatter of SKILL.md; each save creates a new version.',
  新文件路径: 'New file path',
  '只能整体替换，不能在线编辑。': 'It can only be replaced, not edited here.',
  '已回滚到 v{n}，相关 Bot 下一轮生效': 'Rolled back to v{n}; affected Bots pick it up next run',
  '{name} 的历史版本': 'Version history of {name}',
  回滚到此版本: 'Roll Back to This Version',
  'v{n} · {count} 个文件': 'v{n} · {count} {count:file|files}',
} satisfies Record<string, string>
