export default {
  清除: 'Clear',
  搜索: 'Search',
  缩小: 'Zoom out',
  放大: 'Zoom in',
  没有项目: 'No items',
  操作: 'Actions',
  折叠: 'Collapse',
  展开: 'Expand',
  '{n} 条未读': '{n} unread',
  在线: 'Online',
  忙碌: 'Busy',
  离开: 'Away',
  正在载入: 'Loading',
  应用导航: 'App navigation',
  '{label}（{n} 条未读）': '{label} ({n} unread)',
  '{label}（有新内容）': '{label} (new activity)',
  有新内容: 'New activity',
  侧栏: 'Sidebar',
  柱状图: 'bar chart',
  取消: 'Cancel',
  正在处理: 'Working',
  '关闭#close': 'Close',
  '（在新窗口打开）': ' (opens in a new window)',
  帮助: 'Help',
  路径: 'Path',
  显示上层文件夹: 'Show parent folders',
  共工空间: 'Gonggong Space',
  现在: 'now',
  消息: 'Messages',
  关闭通知: 'Dismiss notification',
  '另外 {n} 条通知': '{n} more {n:notification|notifications}',
  请选择: 'Select',
  大写锁定已打开: 'Caps Lock is on',
  隐藏明文: 'Hide password',
  显示明文: 'Show password',
  增加: 'Increase',
  减少: 'Decrease',
  显示选项: 'Show options',
  '移除 {name}': 'Remove {name}',
  将文件拖到这里: 'Drop files here',
  松开以添加: 'Release to add',
  '选择文件…': 'Choose files…',
  上传文件: 'Upload files',
  '{name} 上传进度': '{name} upload progress',
  已上传: 'Uploaded',
  颜色: 'Color',
  '{label}：{color}': '{label}: {color}',
  选择颜色: 'Choose color',
  十六进制颜色: 'Hex color',
  '格式为 #RRGGBB': 'Use the #RRGGBB format',
  '{label}：{v} / {max}': '{label}: {v} / {max}',
  评分: 'Rating',
  '{date} {weekday}': '{weekday}, {date}',
  日历: 'Calendar',
  上个月: 'Previous month',
  今天: 'Today',
  下个月: 'Next month',
  选择日期: 'Choose date',
  '{label}：{value}': '{label}: {value}',
  日期: 'Date',
  未选择: 'Not selected',
  回复: 'Reply',
  回复话题: 'Reply in thread',
  转发: 'Forward',
  拷贝: 'Copy',
  置顶: 'Pin',
  标记为待办: 'Mark as to-do',
  多选: 'Select',
  编辑: 'Edit',
  撤回: 'Recall',
  删除: 'Delete',
  你撤回了一条消息: 'You recalled a message',
  以下为新消息: 'New messages',
  返回: 'Back',
  群设置: 'Group settings',
  群成员: 'Members',
  查看全部: 'View all',
  添加: 'Add',
  话题: 'Thread',
  关闭话题: 'Close thread',
  '{n} 条回复': '{n} {n:reply|replies}',
  同时发送到群: 'Also send to group',
  '{names} 等 {n} 人': '{names} and {more} {more:other|others}',
  添加表情回复: 'Add reaction',
  全部已读: 'Read by all',
  已读: 'Read',
  '{n} 人未读': '{n} unread',
  未读: 'Unread',
  '最后回复 {time}': 'Last reply {time}',
  表情回复: 'React',
  更多: 'More',
  消息操作: 'Message actions',
  正在发送: 'Sending',
  '发送失败，重新发送': 'Failed to send. Resend',
  '发送失败，点按重新发送': 'Failed to send. Click to resend',
  '回复 {name}：': 'Reply to {name}:',
  加急: 'Urgent',
  '（已编辑）': ' (edited)',
  表情: 'Emoji',
  提及: 'Mention',
  图片: 'Image',
  '文件#item': 'File',
  截图: 'Screenshot',
  格式: 'Format',
  取消回复: 'Cancel reply',
  消息输入: 'Message input',
  '发送给 {name}': 'Message {name}',
  'Enter 发送 · ⇧Enter 换行': 'Enter to send · ⇧Enter for new line',
  发送: 'Send',
  '发送（Enter），换行（Shift + Enter）': 'Send (Enter), new line (Shift + Enter)',
  代码: 'Code',
  已复制: 'Copied',
  复制: 'Copy',
  暂停: 'Pause',
  播放语音: 'Play voice message',
  未听: 'Unplayed',
  正在输入: 'typing',
  昨天: 'Yesterday',
  '[加急] ': '[Urgent] ',
  '[有人@我] ': '[Mentioned] ',
  '[草稿] ': '[Draft] ',
  运行中: 'Running',
  已置顶: 'Pinned',
  免打扰: 'Muted',
  有未读: 'Unread',
  '会话#list': 'Conversations',
  上传进度: 'Upload progress',
  下载: 'Download',
  文档: 'Doc',
  表格: 'Sheet',
  多维表格: 'Base',
  幻灯片: 'Slides',
  知识库: 'Wiki',
  思维笔记: 'Mindnote',
  '进行中#live': 'Live',
  已结束: 'Ended',
  即将开始: 'Upcoming',
  '{n} 人在会中': '{n} in meeting',
  '{n} 人参加': '{n} attended',
  '{n} 人受邀': '{n} invited',
  会议号: 'Meeting ID',
  发起人: 'Host',
  时长: 'Duration',
  加入会议: 'Join meeting',
  查看回放: 'View recording',
  你已接受: 'You accepted',
  你已回复待定: 'You replied maybe',
  你已拒绝: 'You declined',
  接受: 'Accept',
  待定: 'Maybe',
  '拒绝#rsvp': 'Decline',
  '{month}{day}日 {weekday}': '{month} {day} {weekday}',
  '{name} 组织 · {n} 人': 'Organized by {name} · {n} {n:person|people}',
  '{name} 组织': 'Organized by {name}',
  '是否参加？': 'Going?',
  回复日程: 'RSVP',
  所有人: 'Everyone',
  '{n} 人': '{n} {n:member|members}',
  选择要提及的人: 'Choose someone to mention',
  '匹配「{query}」': 'Matching "{query}"',
  没有匹配的成员: 'No matching members',
  笑脸: 'Smileys',
  手势: 'Gestures',
  符号: 'Symbols',
  常用: 'Frequent',
  '笑 开心': 'grin happy',
  '大笑 开心': 'laugh happy',
  笑哭: 'tears of joy lol',
  打滚笑: 'rofl',
  '微笑 害羞': 'smile blush',
  微笑: 'smile',
  眨眼: 'wink',
  '喜欢 爱心眼': 'love heart eyes',
  '庆祝 派对': 'party celebrate',
  '酷 墨镜': 'cool sunglasses',
  '思考 想': 'thinking',
  '惊讶 哇': 'wow surprised',
  '尴尬 汗': 'sweat awkward',
  '困 睡觉': 'sleepy sleep',
  '难过 哭': 'sad cry',
  大哭: 'sob',
  生气: 'angry',
  '爆炸 震惊': 'mind blown shocked',
  含泪笑: 'smile tear',
  紧张: 'grimace nervous',
  拥抱: 'hug',
  '敬礼 收到': 'salute roger',
  倒脸: 'upside down',
  天使: 'angel',
  '赞 好 同意': 'thumbs up like agree',
  '踩 不同意': 'thumbs down disagree',
  '好的 OK': 'ok',
  '谢谢 拜托': 'thanks please pray',
  鼓掌: 'clap',
  '举手 庆祝': 'raised hands celebrate',
  '加油 强': 'strong muscle',
  '握手 合作': 'handshake deal',
  '你好 再见 挥手': 'wave hi bye',
  '耶 胜利': 'victory peace',
  '祈祷 好运': 'fingers crossed luck',
  '看 关注': 'eyes look',
  '举手 停': 'hand stop',
  比心: 'heart hands',
  '一 注意': 'point up attention',
  '这里 指': 'point right here',
  '完成 对 已处理': 'done check yes',
  '错 不行': 'cross no wrong',
  '对 可以': 'circle ok',
  '重要 注意': 'important exclamation',
  '问题 疑问': 'question',
  '火 热门': 'fire hot',
  '闪亮 新': 'sparkles new',
  '庆祝 撒花': 'tada celebrate',
  '爱心 喜欢': 'heart love',
  '满分 一百': '100 perfect',
  '闪电 加急': 'zap urgent',
  '火箭 上线 发布': 'rocket launch ship',
  '置顶 固定': 'pin',
  '附件#emoji': 'paperclip attachment',
  '日程 日历': 'calendar date',
  '咖啡 休息': 'coffee break',
  茶: 'tea',
  目标: 'target goal',
  '想法 灯泡': 'idea bulb',
  '闹钟 时间': 'alarm clock time',
  选择表情: 'Choose emoji',
  搜索表情: 'Search emoji',
  表情分类: 'Emoji categories',
  搜索结果: 'Search results',
  没有找到相关表情: 'No emoji found',
  已完成: 'Completed',
  预览: 'Preview',
  群: 'Group',
  机器: 'Machine',
} satisfies Record<string, string>
