export default {
  一致: 'In sync',
  同步中: 'Syncing',
  落后: 'Behind',
  本地有改动: 'Local changes',
  冲突待处理: 'Conflict pending',
  不参与: 'Not participating',
  离线: 'Offline',
  初始: 'Initial',
  自动合并: 'Auto-merged',
  中断: 'Interrupted',
  本地修改: 'Local edit',
  合并: 'Merged',
  '{n} 冲突': '{n} {n:conflict|conflicts}',
  '{n} 同步中': '{n} syncing',
  '{n} 落后': '{n} behind',
  '{n} 本地有改动': '{n} {n:local change|local changes}',
  '{n} 离线': '{n} offline',
  '{a}/{b} 一致': '{a}/{b} in sync',
  同步状态: 'Sync status',
  副本: 'Replicas',
  版本历史: 'Version history',
  还没有副本: 'No replicas yet',
  还没有版本: 'No versions yet',
  '等 {n} 个文件': '({n} {n:file|files} in total)',
  '{n} 个文件': '{n} {n:file|files}',
  加载更多: 'Load more',
  重试: 'Retry',
  '、': ', ',
}
