export default {
  一致: 'In sync',
  同步中: 'Syncing',
  落后: 'Behind',
  本地有改动: 'Local changes',
  冲突待处理: 'Conflict pending',
  提交失败: 'Submit failed',
  不参与: 'Not participating',
  离线: 'Offline',
  初始: 'Initial',
  自动合并: 'Auto-merged',
  中断: 'Interrupted',
  本地修改: 'Local edit',
  合并: 'Merged',
  '{n} 冲突': '{n} {n:conflict|conflicts}',
  '{n} 同步中': '{n} syncing',
  '{n} 落后': '{n} behind',
  '{n} 提交失败': '{n} {n:submit|submits} failed',
  '{n} 本地有改动': '{n} {n:Bot has|Bots have} local changes',
  '{n} 离线': '{n} offline',
  '{a}/{b} 一致': '{a}/{b} in sync',
  同步状态: 'Sync status',
  '各 Bot': 'Bots',
  版本历史: 'Version history',
  还没有版本: 'No versions yet',
  '等 {n} 个文件': '({n} {n:file|files} in total)',
  '{n} 个文件': '{n} {n:file|files}',
  加载更多: 'Load more',
  重试: 'Retry',
  '、': ', ',
  '不参与（本机目录）': 'Not participating (local directory)',
  '不参与（有未提交的改动）': 'Not participating (uncommitted changes)',
  '对齐（机器离线，上线后对齐）': 'Align (machine offline, aligns once it connects)',
  '对齐（工作区就绪后对齐）': 'Align (once its workspace is ready)',
  '不参与（共工空间客户端版本过旧，请升级）':
    'Not participating (Gonggong Space client too old, please upgrade)',
  基准: 'Base',
  对齐: 'Align',
  正在切换为强制同步: 'Switching to force sync',
  '基准 Bot': 'Base Bot',
  '它当前的工作区文件（含未提交改动）生成第一个版本，其他 Bot 的工作区对齐到它':
    "Its current workspace files (uncommitted changes included) become the first version; the other Bots' workspaces align to it",
  '选择基准 Bot': 'Choose the base Bot',
  '没有可作为基准的 Bot': 'No Bot can be the base',
  '切换后各 Bot 的处理方式': 'What happens to each Bot',
  '对齐会把工作区覆盖为基准版本，被覆盖的文件先备份到本机。已在运行的轮次照分区模式跑完，期间的新触发等切换完成后再运行。':
    'Aligning overwrites a workspace with the base version, backing up overwritten files on its machine first. Turns already running finish in partition mode; new triggers run once the switch is done.',
  确认切换: 'Switch',
  '正在切换：等待基准 Bot 提交工作区文件，新触发的轮次稍后运行':
    'Switching: waiting for the base Bot to submit its workspace files; new turns run afterwards',
  '各 Bot 在自己的工作区独立工作，互不同步': 'Each Bot works in its own workspace, nothing is synced',
  切回分区模式: 'Switch back to partition mode',
  '停止同步，各 Bot 保留当前文件各自发展；服务器存档保留 30 天':
    'Stops syncing; each Bot keeps its current files and goes its own way. The server keeps an archive for 30 days',
  '参与的 Bot 工作区保持一致：每轮结束后改动自动分发给其他 Bot（不同步 .git）':
    "Participating Bots' workspaces stay identical: each turn's changes go to the other Bots (.git is not synced)",
  绑定仓库后才能切换为强制同步: 'Bind a repo before switching to force sync',
  切换为强制同步: 'Switch to force sync',
  仅群管理员可切换同步模式: 'Only group admins can switch the sync mode',
  '「{name}」将停止强制同步。': '"{name}" will stop force sync.',
  '各 Bot 保留当前文件，此后各自独立工作':
    'Each Bot keeps its current files and works on its own from now on',
  '同步版本存档保留 30 天后清除': 'The sync version archive is deleted after 30 days',
  '之后可以重新切换为强制同步，届时重新选择基准 Bot':
    'You can switch to force sync again later, picking a base Bot anew',
  已切回分区模式: 'Switched back to partition mode',
  有未提交的改动: 'Uncommitted changes',
  未加入: 'Not joined',
  加入: 'Join',
  丢弃本地改动并加入: 'Discard local changes and join',
  '{bot} 的工作区将与最新版本保持一致。': "{bot}'s workspace will match the latest version.",
  '未提交的改动和最新版本没有的文件会先备份到本机，再被覆盖或删除':
    'Uncommitted changes and files the latest version lacks are backed up on the machine, then overwritten or deleted',
  '备份可在本机桌面端的「工作区」页找到':
    'Backups are on the Workspaces page of the desktop app on that machine',
  丢弃并加入: 'Discard and join',
  已开始加入强制同步: 'Joining force sync',
  已开始加入: 'Joining',
  '或先在本机提交、清理后再加入': 'Or commit and clean up on the machine first, then join',
  下一轮会自动重试: 'The next turn retries automatically',
  可在同步模式设置中切回分区模式以取消: 'To cancel, switch back to partition mode in the sync mode settings',
  同步模式设置: 'Sync mode settings',
  切换中: 'Switching',
  '正在切换为强制同步，等待基准 Bot 提交工作区文件…':
    'Switching to force sync, waiting for the base Bot to submit its workspace files…',
  '我的改动（相对 v{v}）': 'My changes (from v{v})',
  '最新版本的改动（v{v}）': 'Changes in the latest version (v{v})',
  二进制文件: 'Binary file',
  收起预览: 'Hide preview',
  '{path} 的处理方式': 'What to do with {path}',
  保留我的: 'Keep mine',
  采用最新: 'Take latest',
  '交给 Bot 合并': 'Let the Bot merge',
  '已交给 {bot} 合并': 'Handed to {bot} to merge',
  已提交处理: 'Submitted',
  '处理 {bot} 的同步冲突': "Resolve {bot}'s sync conflict",
  '基于 v{base} 的改动与 v{head} 冲突：{n} 个文件':
    'Changes made on v{base} conflict with v{head}: {n} {n:file|files}',
  整版丢弃: 'Discard all',
  提交: 'Submit',
  冲突已处理: 'The conflict was already resolved',
  '选「交给 Bot 合并」的文件会写入冲突标记，由 {bot} 发起一轮合并，结束后自动提交':
    'Files set to "Let the Bot merge" get conflict markers; {bot} runs a merge turn and its result is submitted automatically',
  '保留我的：以我的内容为准；采用最新：放弃我对该文件的改动':
    'Keep mine: my content wins. Take latest: my change to that file is dropped',
  '{bot} 这次的改动将全部放弃，工作区回到最新版本。':
    "All of {bot}'s held changes are dropped and its workspace returns to the latest version.",
  被放弃的文件会先备份到本机: 'Dropped files are backed up on the machine first',
  已丢弃冲突改动: 'Conflicting changes discarded',
  处理: 'Resolve',
  '提交为 v{v}（自动合并）': 'Submitted as v{v} (auto-merged)',
  '提交为 v{v}': 'Submitted as v{v}',
  '无文件改动 · v{v}': 'No file changes · v{v}',
  '冲突待处理 · {n} 个文件': 'Conflict pending · {n} {n:file|files}',
  '同步失败：{reason}': 'Sync failed: {reason}',
  等待处理本地改动: 'Waiting for local changes to be settled',
  等待处理同步冲突: 'Waiting for the sync conflict to be resolved',
  已开始提交本地改动: 'Submitting local changes',
  提交本地改动: 'Submit local changes',
  丢弃本地改动: 'Discard local changes',
  处理冲突: 'Resolve conflict',
  '{bot} 的工作区将回到最新版本。': "{bot}'s workspace will return to the latest version.",
  '本地改动的文件会先备份到本机，再被覆盖或删除':
    'Locally changed files are backed up on the machine first, then overwritten or deleted',
  丢弃: 'Discard',
  已开始丢弃本地改动: 'Discarding local changes',
}
