export default {
  重试: 'Retry',
  取消: 'Cancel',
  移出: 'Remove',
  '已移出 {name}': 'Removed {name}',
  '{scope} {n} 人': '{scope} ({n} {n:person|people})',
  私聊设置: 'Chat settings',
  群设置: 'Group settings',
  '群成员 · {n}': 'Members · {n}',
  仓库与工作区: 'Repo & workspaces',
  群名称与公告: 'Group name & notice',
  群公告: 'Group notice',
  预览与服务: 'Previews & services',
  已退出群: 'Left the group',
  已删除私聊: 'Chat deleted',
  群已解散: 'Group dissolved',
  确认退出: 'Confirm leave',
  退出群: 'Leave group',
  '你是唯一的群管理员，退出前先在「群成员」里指定其他群管理员。':
    'You are the only group admin. Appoint another group admin under "Members" before leaving.',
  '退出后你的 Bot 一并移出本群；持锁中的轮次按非主动中断处理。再次点击确认。':
    'Your Bots leave the group with you; a turn holding the lock is treated as interrupted. Click again to confirm.',
  确认删除: 'Confirm delete',
  删除私聊: 'Delete chat',
  确认解散: 'Confirm dissolve',
  解散群: 'Dissolve group',
  '删除后消息与审计记录保留；Bot 的托管工作区保留在本机，由你决定是否删除。再次点击确认。':
    "Messages and audit records are kept; the Bot's managed workspace stays on your machine for you to delete or keep. Click again to confirm.",
  '解散后群归档，消息与审计记录保留；强制同步群的存档 30 天后清除；各 Bot 的托管工作区保留，由主人决定是否删除。再次点击确认。':
    "The group is archived with its messages and audit records; force-sync archives are purged after 30 days; each Bot's managed workspace is kept for its owner to delete or keep. Click again to confirm.",
  '未绑定仓库 · 各 Bot 使用本机目录': 'No repo · each Bot uses a local folder',
  成员: 'Members',
  公告: 'Notice',
  设置: 'Settings',
  '{n} 个': '{n}',
  未绑定: 'Not set',
  '{n} 个预览': '{n} {n:preview|previews}',
  已隐藏: 'Hidden',
  暂无: 'None',
  消息免打扰: 'Mute messages',
  '普通消息不提醒；@我、我的 Bot 待审批、向我提问、锁轮到我仍提醒':
    "No alerts for regular messages; still alerts for @me, my Bots' approvals, questions to me and my lock turn",
  置顶群: 'Pin group',
  运行卡片默认折叠: 'Collapse run cards by default',
  '只对我生效，审批与提问卡片始终展开': 'Only for me; approval and question cards stay expanded',
  群管理: 'Group admin',
  你是群管理员: 'You are a group admin',
  '仅群管理员 · {names}': 'Group admins only · {names}',
  '、': ', ',
  仓库与基准分支: 'Repo & base branch',
  同步模式: 'Sync mode',
  群级参数: 'Group parameters',
  群级参数加载失败: 'Failed to load group parameters',
  搜索成员: 'Search members',
  添加成员: 'Add member',
  成员列表加载失败: 'Failed to load members',
  所有账号都已在群里: 'Every account is already in the group',
  '（我）': ' (me)',
  群管理员: 'Group admin',
  '带入 {bots}': 'Brought {bots}',
  '未带入 Bot': 'No Bots brought',
  取消管理员: 'Remove admin',
  设为管理员: 'Make admin',
  '移出成员时，其 Bot 一并移出；持锁中的 Bot 按非主动中断处理。':
    'Removing a member also removes their Bots; a Bot holding the lock is treated as interrupted.',
  '移出成员 {name}': 'Remove member {name}',
  '其 Bot 一并移出本群；持锁中的 Bot 按非主动中断处理。':
    'Their Bots leave the group too; a Bot holding the lock is treated as interrupted.',
  '{n} 个 · 在线 {online}': '{n} · {online} online',
  '拉入 Bot': 'Add Bot',
  ' · 主人将一并加入': ' · owner joins too',
  '{agent} · 主人 {owner}': '{agent} · owner {owner}',
  '档位 {tier}': 'Tier {tier}',
  ' · 本群': ' · this group',
  '触发 {scope}': 'Trigger {scope}',
  全局设置: 'Global settings',
  '档位默认跟随 Bot 全局设置，Bot 主人可为本群单独指定，运行中的轮次立即生效；本群为「完全访问」时仅指定名单可触发。 想少审批，Bot 主人可在 Bot 详情的「命令审批」中开启白名单或全部自动。移出后保留工作区，由主人决定是否删除。':
    'The tier follows the Bot\'s global setting by default; the Bot owner can set one for this group, taking effect on running turns at once. At "Full access" in this group only the listed people can trigger it. For fewer approvals, the owner can enable an allowlist or auto-approve all under "Command approval" in the Bot details. Removing a Bot keeps its workspace for the owner to delete or keep.',
  '移出 Bot {name}': 'Remove Bot {name}',
  '移出后保留其工作区，由主人决定是否删除；运行中的轮次按非主动中断处理。':
    'Its workspace is kept for the owner to delete or keep; a running turn is treated as interrupted.',
  编辑公告: 'Edit notice',
  发布公告: 'Post notice',
  群公告加载失败: 'Failed to load notices',
  暂无群公告: 'No notices yet',
  '当前 · 已隐藏': 'Current · hidden',
  当前: 'Current',
  移除: 'Remove',
  在对话顶部显示: 'Show atop the chat',
  不再显示: "Don't show again",
  '群管理员移除的公告对所有人隐藏；成员「不再显示」只对自己生效，发布新公告后重新显示。':
    'A notice removed by a group admin is hidden for everyone; "Don\'t show again" only hides it for you, until a new notice is posted.',
  '跟随全局（{tier}）': 'Follow global ({tier})',
  本群档位: 'Tier in this group',
  群名称: 'Group name',
  '群公告 · 置顶展示在对话顶部': 'Group notice · pinned atop the chat',
  '如：每个 Bot 独立分支，走 PR；退款 v1 下周一下线':
    'e.g. Each Bot on its own branch, merge via PR; refunds v1 retires next Monday',
  保存: 'Save',
  移除群公告: 'Remove group notice',
  '移除后所有成员都不再看到这条公告，仍可在群设置「群公告」中查看历史。':
    'No member will see this notice anymore; its history stays under "Group notice" in group settings.',
  '已隐藏，可在群设置「群公告」中查看': 'Hidden. Find it under "Group notice" in group settings',
  '权限审批等待 · 分区（分钟）': 'Approval wait (minutes)',
  '接力链长上限（跳）': 'Max relay chain length (hops)',
  'Bot 离线等待上线（分钟）': 'Wait for offline Bot (minutes)',
  基本信息: 'General',
  '成员与 Bot': 'Members & Bots',
  '参数#settings': 'Parameters',
  群级参数已保存: 'Group parameters saved',
  保存后对新会话生效: 'Applies to new sessions after saving',
  当前模式: 'Current mode',
  '切换到强制同步后，同一时刻只有一个写入者，每轮结束后所有在线机器的工作树保持一致（不同步 .git）。':
    'With force sync there is one writer at a time, and after each turn every online machine has the same working tree (.git is not synced).',
  强制同步暂未开放: 'Force sync is not available yet',
  切换到强制同步: 'Switch to force sync',
  私聊名: 'Chat name',
  群名: 'Group name',
  类型: 'Type',
  '私聊 · 仅你和你的 Bot，不能邀请他人': 'Private chat · only you and your Bots; no one else can be invited',
  '{name}（我）': '{name} (me)',
  '添加 Bot': 'Add Bot',
  '可添加的 Bot': 'Bots you can add',
  '{state}，暂不能拉入': "{state}; can't be added yet",
  '还没有可拉入的 Bot': 'No Bots to add yet',
  没有可添加的成员: 'No members to add',
  '审批 {min} 分 · 接力 {hops} 跳': 'Approval {min} min · relay {hops} {hops:hop|hops}',
} satisfies Record<string, string>
