//! Machine-local model providers (design §4.2/§4.3): third-party endpoints and keys per agent in
//! `<home>/providers.json` (0600), the machine default per agent, per-bot overrides and the provider each ACP session
//! was started with. Never sent anywhere unmasked: whatever leaves the machine goes through [`Store::view`].
use crate::protocol::AgentKind;
use crate::t;
use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

/// The CLI's own login and user-level config: nothing is injected.
pub const OFFICIAL: &str = "official";
/// A bot without an override follows the machine default.
pub const INHERIT: &str = "inherit";
pub const OFFICIAL_NAME: &str = "官方登录";
pub const AUTH_TOKEN: &str = "ANTHROPIC_AUTH_TOKEN";
pub const API_KEY: &str = "ANTHROPIC_API_KEY";
pub const WIRE_RESPONSES: &str = "responses";

/// Claude env keys carried besides the connection keys (§4.2.1).
pub const EXTRA_ENV: [&str; 6] = [
    "CLAUDE_CODE_MAX_CONTEXT_TOKENS",
    "CLAUDE_CODE_AUTO_COMPACT_WINDOW",
    "CLAUDE_CODE_MAX_OUTPUT_TOKENS",
    "CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS",
    "ENABLE_TOOL_SEARCH",
    "ANTHROPIC_SMALL_FAST_MODEL",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PresetGroup {
    Cn,
    Aggregator,
    Global,
}

/// Claude Code's haiku/sonnet/opus aliases (`ANTHROPIC_DEFAULT_*_MODEL`).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModelMap {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub haiku: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sonnet: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opus: Option<String>,
}

/// A built-in vendor from `presets/providers.json` (generated by `scripts/sync-provider-presets.mjs`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Preset {
    pub id: String,
    pub agent: AgentKind,
    pub name: String,
    pub group: PresetGroup,
    #[serde(default)]
    pub website_url: Option<String>,
    #[serde(default)]
    pub api_key_url: Option<String>,
    pub base_url: String,
    #[serde(default)]
    pub api_key_field: Option<String>,
    #[serde(default)]
    pub model: Option<String>,
    #[serde(default)]
    pub models: Option<ModelMap>,
    #[serde(default)]
    pub model_options: Vec<String>,
    #[serde(default)]
    pub env: BTreeMap<String, String>,
    #[serde(default)]
    pub wire_api: Option<String>,
    #[serde(default)]
    pub effort: Option<String>,
}

#[derive(Deserialize)]
struct PresetFile {
    source: String,
    presets: Vec<Preset>,
}

fn preset_file() -> &'static PresetFile {
    static FILE: OnceLock<PresetFile> = OnceLock::new();
    FILE.get_or_init(|| {
        serde_json::from_str(include_str!("../presets/providers.json")).expect("bundled presets/providers.json")
    })
}

/// e.g. `cc-switch@36d9504`.
pub fn presets_source() -> &'static str {
    &preset_file().source
}

pub fn presets(agent: Option<AgentKind>) -> impl Iterator<Item = &'static Preset> {
    preset_file().presets.iter().filter(move |p| agent.is_none_or(|a| p.agent == a))
}

pub fn preset(agent: AgentKind, id: &str) -> Option<&'static Preset> {
    presets(Some(agent)).find(|p| p.id == id)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SourceKind {
    CcSwitch,
    Link,
}

/// Where an imported provider came from; CC Switch ids let a re-import update it instead of duplicating it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Source {
    pub kind: SourceKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Provider {
    pub id: String,
    pub agent: AgentKind,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preset_id: Option<String>,
    /// Bumped on every change so running adapters can tell they must restart.
    pub revision: u32,
    pub base_url: String,
    pub api_key: String,
    /// Claude only: which variable carries the key ([`AUTH_TOKEN`] or [`API_KEY`]).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key_field: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub models: Option<ModelMap>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub env: BTreeMap<String, String>,
    /// `http(s)://[user:pass@]host:port` the agent reaches the provider through; `None` = direct.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proxy: Option<String>,
    /// Codex only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wire_api: Option<String>,
    /// Codex only: `model_reasoning_effort`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effort: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<Source>,
}

impl Provider {
    /// A new provider (no id yet) copying the preset's values; later preset updates never touch it.
    pub fn from_preset(preset: &Preset, api_key: String) -> Provider {
        Provider {
            name: preset.name.clone(),
            preset_id: Some(preset.id.clone()),
            model: preset.model.clone(),
            models: preset.models.clone(),
            env: preset.env.clone(),
            api_key_field: preset.api_key_field.clone(),
            wire_api: preset.wire_api.clone(),
            effort: preset.effort.clone(),
            ..Provider::custom(preset.agent, preset.name.clone(), preset.base_url.clone(), api_key)
        }
    }

    pub fn custom(agent: AgentKind, name: String, base_url: String, api_key: String) -> Provider {
        Provider {
            id: String::new(),
            agent,
            name,
            preset_id: None,
            revision: 0,
            base_url,
            api_key,
            api_key_field: (agent == AgentKind::Claude).then(|| AUTH_TOKEN.into()),
            model: None,
            models: None,
            env: BTreeMap::new(),
            proxy: None,
            wire_api: (agent == AgentKind::Codex).then(|| WIRE_RESPONSES.into()),
            effort: None,
            source: None,
        }
    }

    fn validate(&self) -> Result<()> {
        if self.name.trim().is_empty() {
            bail!(t!("供应商名称不能为空"));
        }
        if !(self.base_url.starts_with("https://") || self.base_url.starts_with("http://")) {
            bail!(t!("Base URL 必须以 http:// 或 https:// 开头"));
        }
        if self.api_key.trim().is_empty() {
            bail!(t!("API Key 不能为空"));
        }
        validate_extras(&self.env, self.proxy.as_deref())
    }

    pub fn process_env(&self) -> BTreeMap<String, String> {
        process_env(&self.env, self.proxy.as_deref())
    }

    fn same_connection(&self, other: &Provider) -> bool {
        self.agent == other.agent
            && self.base_url.trim_end_matches('/') == other.base_url.trim_end_matches('/')
            && self.api_key == other.api_key
    }

    pub fn view(&self) -> ProviderView {
        ProviderView {
            id: self.id.clone(),
            agent: self.agent,
            name: self.name.clone(),
            preset_id: self.preset_id.clone(),
            revision: self.revision,
            base_url: self.base_url.clone(),
            api_key: mask_key(&self.api_key),
            api_key_field: self.api_key_field.clone(),
            model: self.model.clone(),
            models: self.models.clone(),
            env: self.env.clone(),
            proxy: self.proxy.as_deref().map(mask_proxy),
            wire_api: self.wire_api.clone(),
            effort: self.effort.clone(),
            source: self.source.clone(),
        }
    }
}

/// The agent process's env as if exported in a terminal: the proxy (both cases, loopback direct so the agent still
/// reaches the daemon's local MCP endpoint), then the user's own variables.
fn process_env(vars: &BTreeMap<String, String>, proxy: Option<&str>) -> BTreeMap<String, String> {
    let mut env = vars.clone();
    if let Some(url) = proxy {
        for k in ["HTTP_PROXY", "HTTPS_PROXY", "http_proxy", "https_proxy"] {
            env.entry(k.into()).or_insert_with(|| url.into());
        }
        let user = vars.get("NO_PROXY").or(vars.get("no_proxy"));
        let bypass = ["localhost", "127.0.0.1", "::1"].into_iter().chain(user.map(String::as_str)).collect::<Vec<_>>();
        env.insert("NO_PROXY".into(), bypass.join(","));
        env.insert("no_proxy".into(), bypass.join(","));
    }
    env
}

fn validate_extras(env: &BTreeMap<String, String>, proxy: Option<&str>) -> Result<()> {
    if let Some(k) = env.keys().find(|k| !env_name(k)) {
        bail!(t!("环境变量名不合法：{name}", name = k));
    }
    if proxy.is_some_and(|u| !(u.starts_with("http://") || u.starts_with("https://"))) {
        bail!(t!("代理地址必须以 http:// 或 https:// 开头"));
    }
    Ok(())
}

/// What an agent's official login runs with besides the CLI's own config: extra variables and a proxy.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct Official {
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    pub env: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy: Option<String>,
}

impl Official {
    pub fn is_empty(&self) -> bool {
        self.env.is_empty() && self.proxy.is_none()
    }

    pub fn process_env(&self) -> BTreeMap<String, String> {
        process_env(&self.env, self.proxy.as_deref())
    }

    /// Password masked, as for a provider.
    pub fn view(&self) -> OfficialView {
        OfficialView { env: self.env.clone(), proxy: self.proxy.as_deref().map(mask_proxy) }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OfficialView {
    pub env: BTreeMap<String, String>,
    pub proxy: Option<String>,
}

/// Keys leave the machine as their last 4 characters at most; short ones not at all.
pub fn mask_key(key: &str) -> String {
    let chars: Vec<char> = key.chars().collect();
    if chars.len() <= 8 {
        return "****".into();
    }
    format!("****{}", chars[chars.len() - 4..].iter().collect::<String>())
}

pub fn env_name(k: &str) -> bool {
    k.chars().next().is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && k.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// A proxy leaves the machine with its password masked.
pub fn mask_proxy(proxy: &str) -> String {
    match url::Url::parse(proxy) {
        Ok(mut u) if u.password().is_some() => {
            let _ = u.set_password(Some("****"));
            u.to_string().trim_end_matches('/').to_string()
        }
        _ => proxy.to_string(),
    }
}

/// [`Provider`] without the key, for the server, the Web and the logs.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderView {
    pub id: String,
    pub agent: AgentKind,
    pub name: String,
    pub preset_id: Option<String>,
    pub revision: u32,
    pub base_url: String,
    pub api_key: String,
    pub api_key_field: Option<String>,
    pub model: Option<String>,
    pub models: Option<ModelMap>,
    pub env: BTreeMap<String, String>,
    pub proxy: Option<String>,
    pub wire_api: Option<String>,
    pub effort: Option<String>,
    pub source: Option<Source>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StoreView {
    pub machine: BTreeMap<AgentKind, String>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub official: BTreeMap<AgentKind, OfficialView>,
    pub bots: BTreeMap<String, String>,
    pub providers: Vec<ProviderView>,
    /// Latest session of each (group, bot), so a switch can say which groups keep the old provider.
    pub sessions: Vec<SessionView>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionView {
    pub group_id: String,
    pub bot_id: String,
    pub agent: AgentKind,
    /// A provider id or [`OFFICIAL`].
    pub provider: String,
}

/// The provider a new ACP session was started with; resuming it keeps using it (§4.3).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionPin {
    /// A provider id or [`OFFICIAL`].
    pub provider: String,
    pub agent: AgentKind,
    pub group_id: String,
    pub bot_id: String,
    pub pinned_at: i64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Selection {
    /// Carries the agent's [`Official`] extras so a change to them restarts the adapter like a provider edit.
    Official(Official),
    Provider(Box<Provider>),
}

impl Selection {
    /// What `machine`, `bots` and session pins store.
    pub fn key(&self) -> &str {
        match self {
            Selection::Official(_) => OFFICIAL,
            Selection::Provider(p) => &p.id,
        }
    }

    pub fn name(&self) -> &str {
        match self {
            Selection::Official(_) => OFFICIAL_NAME,
            Selection::Provider(p) => &p.name,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RunPlan {
    /// Resume the session with the provider it was pinned to, whatever the settings say now.
    Resume(Selection),
    /// Start a new session with the effective provider (then [`Store::pin`] it). `provider_removed`: the session to
    /// resume was pinned to a provider that no longer exists (`newSessionReason = 'provider_removed'`).
    New { selection: Selection, provider_removed: bool },
}

/// A (group, bot) whose current session uses another provider than a new session would.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Stale {
    pub group_id: String,
    pub bot_id: String,
    pub session_id: String,
    pub session: String,
    pub effective: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Store {
    /// Machine default per agent: a provider id or [`OFFICIAL`]; absent = official.
    pub machine: BTreeMap<AgentKind, String>,
    /// Official login extras per agent; absent = none.
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    pub official: BTreeMap<AgentKind, Official>,
    /// Per-bot override: a provider id or [`OFFICIAL`]; absent = inherit the machine default.
    pub bots: BTreeMap<String, String>,
    pub providers: Vec<Provider>,
    /// ACP session id → pin.
    pub sessions: BTreeMap<String, SessionPin>,
}

impl Store {
    pub fn path(home: &Path) -> PathBuf {
        home.join("providers.json")
    }

    pub fn load(home: &Path) -> Result<Store> {
        match std::fs::read_to_string(Self::path(home)) {
            Ok(s) => serde_json::from_str(&s).context(t!("providers.json 已损坏")),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Store::default()),
            Err(e) => Err(e.into()),
        }
    }

    /// Atomic (temp file + rename) and owner-only from the first byte.
    pub fn save(&self, home: &Path) -> Result<()> {
        std::fs::create_dir_all(home)?;
        let path = Self::path(home);
        let tmp = path.with_extension(format!("json.{}.tmp", std::process::id()));
        let mut options = std::fs::OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        std::os::unix::fs::OpenOptionsExt::mode(&mut options, 0o600);
        // A leftover from a crashed write under a reused pid.
        let _ = std::fs::remove_file(&tmp);
        let written = (|| {
            let mut file = options.open(&tmp)?;
            file.write_all(&serde_json::to_vec_pretty(self)?)?;
            file.sync_all()?;
            std::fs::rename(&tmp, &path)?;
            anyhow::Ok(())
        })();
        if written.is_err() {
            let _ = std::fs::remove_file(&tmp);
        }
        written
    }

    /// Load, change and save under `<home>/providers.lock`, so the CLI, the desktop app and the daemon never lose
    /// each other's writes.
    pub fn update<T>(home: &Path, f: impl FnOnce(&mut Store) -> Result<T>) -> Result<T> {
        std::fs::create_dir_all(home)?;
        let lock =
            std::fs::OpenOptions::new().write(true).create(true).truncate(false).open(home.join("providers.lock"))?;
        lock.lock()?;
        let mut store = Store::load(home)?;
        let out = f(&mut store)?;
        store.save(home)?;
        Ok(out)
    }

    pub fn get(&self, id: &str) -> Option<&Provider> {
        self.providers.iter().find(|p| p.id == id)
    }

    fn get_for(&self, agent: AgentKind, id: &str) -> Result<&Provider> {
        let p = self.get(id).with_context(|| t!("供应商 {id} 不存在", id = id))?;
        if p.agent != agent {
            bail!(t!(
                "供应商 {name} 属于 {owner}，不能用于 {agent}",
                name = p.name,
                owner = agent_name(p.agent),
                agent = agent_name(agent)
            ));
        }
        Ok(p)
    }

    /// Stores a new provider under a fresh id (returned) at revision 1.
    pub fn add(&mut self, mut p: Provider) -> Result<String> {
        p.validate()?;
        let base = slug(p.preset_id.as_deref().unwrap_or(&p.name));
        p.id = loop {
            let id = format!("{base}-{}", &uuid::Uuid::new_v4().simple().to_string()[..4]);
            if self.get(&id).is_none() {
                break id;
            }
        };
        p.revision = 1;
        self.providers.push(p);
        Ok(self.providers.last().unwrap().id.clone())
    }

    /// Edits in place; the revision goes up when anything changed.
    pub fn edit(&mut self, id: &str, f: impl FnOnce(&mut Provider)) -> Result<()> {
        let p = self.providers.iter_mut().find(|p| p.id == id).with_context(|| t!("供应商 {id} 不存在", id = id))?;
        let mut next = p.clone();
        f(&mut next);
        next.validate()?;
        if next != *p {
            next.revision = p.revision + 1;
            *p = next;
        }
        Ok(())
    }

    /// Defaults and overrides pointing at it fall back (official / inherit); sessions pinned to it keep the id so
    /// [`Store::resolve_run`] reports it as removed.
    pub fn remove(&mut self, id: &str) -> Result<Provider> {
        let i = self.providers.iter().position(|p| p.id == id).with_context(|| t!("供应商 {id} 不存在", id = id))?;
        self.machine.retain(|_, v| v != id);
        self.bots.retain(|_, v| v != id);
        Ok(self.providers.remove(i))
    }

    /// The stored provider `p` duplicates: same CC Switch source, else same agent + Base URL + key.
    pub fn duplicate_of(&self, p: &Provider) -> Option<&Provider> {
        let same_source = |q: &&Provider| {
            q.agent == p.agent && p.source.as_ref().is_some_and(|s| s.id.is_some() && q.source.as_ref() == Some(s))
        };
        self.providers.iter().find(same_source).or_else(|| self.providers.iter().find(|q| q.same_connection(p)))
    }

    /// Adds `p`, or updates its [`Store::duplicate_of`].
    pub fn upsert(&mut self, mut p: Provider) -> Result<String> {
        let Some(id) = self.duplicate_of(&p).map(|q| q.id.clone()) else { return self.add(p) };
        p.validate()?;
        let q = self.providers.iter_mut().find(|q| q.id == id).unwrap();
        p.id = q.id.clone();
        p.revision = q.revision;
        p.preset_id = q.preset_id.clone();
        if p != *q {
            p.revision += 1;
            *q = p;
        }
        Ok(q.id.clone())
    }

    /// `choice`: a provider id of this agent or [`OFFICIAL`].
    pub fn use_machine(&mut self, agent: AgentKind, choice: &str) -> Result<()> {
        if choice != OFFICIAL {
            self.get_for(agent, choice)?;
        }
        self.machine.insert(agent, choice.into());
        Ok(())
    }

    /// `agent` is the bot's `agentKind`; `choice`: a provider id of that agent, [`OFFICIAL`] or [`INHERIT`].
    pub fn use_bot(&mut self, bot_id: &str, agent: AgentKind, choice: &str) -> Result<()> {
        match choice {
            INHERIT => {
                self.bots.remove(bot_id);
                return Ok(());
            }
            OFFICIAL => {}
            id => {
                self.get_for(agent, id)?;
            }
        }
        self.bots.insert(bot_id.into(), choice.into());
        Ok(())
    }

    pub fn official(&self, agent: AgentKind) -> Official {
        self.official.get(&agent).cloned().unwrap_or_default()
    }

    pub fn set_official(&mut self, agent: AgentKind, official: Official) -> Result<()> {
        validate_extras(&official.env, official.proxy.as_deref())?;
        if official.is_empty() {
            self.official.remove(&agent);
        } else {
            self.official.insert(agent, official);
        }
        Ok(())
    }

    fn select(&self, agent: AgentKind, key: &str) -> Result<Selection> {
        match key {
            OFFICIAL => Ok(Selection::Official(self.official(agent))),
            id => Ok(Selection::Provider(Box::new(self.get_for(agent, id)?.clone()))),
        }
    }

    pub fn machine_default(&self, agent: AgentKind) -> Result<Selection> {
        self.select(agent, self.machine.get(&agent).map_or(OFFICIAL, String::as_str))
    }

    /// Bot override, else the machine default, else official.
    pub fn effective(&self, agent: AgentKind, bot_id: &str) -> Result<Selection> {
        match self.bots.get(bot_id) {
            Some(key) => self.select(agent, key),
            None => self.machine_default(agent),
        }
    }

    /// Which provider a run uses. `resume`: the ACP session the run continues, if any.
    pub fn resolve_run(&self, agent: AgentKind, bot_id: &str, resume: Option<&str>) -> Result<RunPlan> {
        let Some(session) = resume else {
            return Ok(RunPlan::New { selection: self.effective(agent, bot_id)?, provider_removed: false });
        };
        Ok(match self.sessions.get(session).map(|pin| pin.provider.as_str()) {
            // Sessions started before providers existed ran on the official login.
            None | Some(OFFICIAL) => RunPlan::Resume(Selection::Official(self.official(agent))),
            Some(id) => match self.get(id) {
                Some(p) => RunPlan::Resume(Selection::Provider(Box::new(p.clone()))),
                None => RunPlan::New { selection: self.effective(agent, bot_id)?, provider_removed: true },
            },
        })
    }

    pub fn pin(&mut self, session_id: &str, agent: AgentKind, group_id: &str, bot_id: &str, selection: &Selection) {
        let pin = SessionPin {
            provider: selection.key().into(),
            agent,
            group_id: group_id.into(),
            bot_id: bot_id.into(),
            pinned_at: chrono::Utc::now().timestamp_millis(),
        };
        self.sessions.insert(session_id.into(), pin);
    }

    /// The latest session (id, pin) of each (group, bot).
    fn latest_sessions(&self) -> Vec<(&String, &SessionPin)> {
        let mut latest: BTreeMap<(&str, &str), (&String, &SessionPin)> = BTreeMap::new();
        for (id, pin) in &self.sessions {
            let slot = latest.entry((&pin.group_id, &pin.bot_id)).or_insert((id, pin));
            if pin.pinned_at > slot.1.pinned_at {
                *slot = (id, pin);
            }
        }
        latest.into_values().collect()
    }

    /// The latest session of each (group, bot) whose provider differs from what a new session would use. Sessions
    /// pinned to a removed provider are left out: their next run starts a new session anyway.
    pub fn stale(&self) -> Result<Vec<Stale>> {
        let mut out = vec![];
        for (id, pin) in self.latest_sessions() {
            if pin.provider != OFFICIAL && self.get(&pin.provider).is_none() {
                continue;
            }
            let session = self.select(pin.agent, &pin.provider)?;
            let effective = self.effective(pin.agent, &pin.bot_id)?;
            if session.key() != effective.key() {
                out.push(Stale {
                    group_id: pin.group_id.clone(),
                    bot_id: pin.bot_id.clone(),
                    session_id: id.clone(),
                    session: session.name().into(),
                    effective: effective.name().into(),
                });
            }
        }
        Ok(out)
    }

    pub fn view(&self) -> StoreView {
        StoreView {
            machine: self.machine.clone(),
            official: self.official.iter().map(|(a, o)| (*a, o.view())).collect(),
            bots: self.bots.clone(),
            providers: self.providers.iter().map(Provider::view).collect(),
            sessions: self
                .latest_sessions()
                .into_iter()
                .map(|(_, pin)| SessionView {
                    group_id: pin.group_id.clone(),
                    bot_id: pin.bot_id.clone(),
                    agent: pin.agent,
                    provider: pin.provider.clone(),
                })
                .collect(),
        }
    }
}

fn agent_name(agent: AgentKind) -> &'static str {
    match agent {
        AgentKind::Claude => "claude",
        AgentKind::Codex => "codex",
    }
}

fn slug(s: &str) -> String {
    let slug: String = s
        .to_lowercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("-");
    if slug.is_empty() { "provider".into() } else { slug }
}

#[cfg(test)]
mod tests {
    use super::*;
    use AgentKind::{Claude, Codex};

    const KEY: &str = "sk-secret-0123456789abcd";

    fn kimi(store: &mut Store) -> String {
        store.add(Provider::from_preset(preset(Claude, "kimi-coding").unwrap(), KEY.into())).unwrap()
    }

    #[test]
    fn process_env_is_the_proxy_then_the_providers_env() {
        let mut p = Provider::custom(Codex, "x".into(), "https://x.test".into(), KEY.into());
        p.env.insert("FOO".into(), "1".into());
        assert_eq!(p.process_env(), BTreeMap::from([("FOO".into(), "1".into())]), "no proxy: direct");

        p.proxy = Some("http://127.0.0.1:7890".into());
        p.env.insert("no_proxy".into(), "corp.cn, 10.0.0.0/8".into());
        p.env.insert("HTTPS_PROXY".into(), "http://other:8080".into());
        let env = p.process_env();
        assert_eq!(env["HTTP_PROXY"], "http://127.0.0.1:7890");
        assert_eq!(env["http_proxy"], "http://127.0.0.1:7890");
        assert_eq!(env["https_proxy"], "http://127.0.0.1:7890");
        assert_eq!(env["HTTPS_PROXY"], "http://other:8080", "the provider's own variables win");
        assert_eq!(env["NO_PROXY"], "localhost,127.0.0.1,::1,corp.cn, 10.0.0.0/8", "loopback stays direct");
        assert_eq!(env["no_proxy"], env["NO_PROXY"]);
        assert_eq!(env["FOO"], "1");
    }

    #[test]
    fn a_proxy_must_be_an_http_url() {
        let mut p = Provider::custom(Codex, "x".into(), "https://x.test".into(), KEY.into());
        p.proxy = Some("127.0.0.1:7890".into());
        assert!(Store::default().add(p.clone()).is_err());
        p.proxy = Some("socks5://127.0.0.1:7890".into());
        assert!(Store::default().add(p.clone()).is_err());
        p.proxy = Some("http://user:pw@127.0.0.1:7890".into());
        Store::default().add(p).unwrap();
    }

    #[test]
    fn bundled_presets_load_and_filter_by_agent() {
        assert!(presets_source().starts_with("cc-switch@"));
        let claude: Vec<_> = presets(Some(Claude)).collect();
        let codex: Vec<_> = presets(Some(Codex)).collect();
        assert!(!claude.is_empty() && !codex.is_empty());
        assert!(claude.iter().all(|p| p.agent == Claude && p.api_key_field.is_some()));
        assert!(codex.iter().all(|p| p.agent == Codex && p.wire_api.as_deref() == Some(WIRE_RESPONSES)));
        assert_eq!(presets(None).count(), claude.len() + codex.len());
        let zhipu = preset(Codex, "zhipu").unwrap();
        assert_eq!(zhipu.name, "智谱 GLM");
        assert!(zhipu.model_options.contains(&"glm-5.3".to_string()));
        assert!(preset(Claude, "xai").is_none(), "xAI is codex-only");
        let mut urls = presets(None).flat_map(|p| [&p.website_url, &p.api_key_url]).flatten();
        assert!(urls.all(|u| !u.contains("aff=") && !u.contains("ref=")), "referral params stripped");
        let mut ids: Vec<_> = presets(None).map(|p| (p.agent, &p.id)).collect();
        ids.sort();
        ids.dedup();
        assert_eq!(ids.len(), presets(None).count(), "ids unique per agent");
    }

    #[test]
    fn from_preset_copies_values_and_add_assigns_id() {
        let mut store = Store::default();
        let id = kimi(&mut store);
        let p = store.get(&id).unwrap();
        assert!(id.starts_with("kimi-coding-"));
        assert_eq!((p.revision, p.preset_id.as_deref()), (1, Some("kimi-coding")));
        assert_eq!(p.base_url, "https://api.kimi.com/coding/");
        assert_eq!(p.env.get("CLAUDE_CODE_MAX_CONTEXT_TOKENS").map(String::as_str), Some("262144"));
        let empty = Provider::custom(Codex, "X".into(), "https://x.test/v1".into(), " ".into());
        assert!(store.add(empty).is_err());
        let bad = Provider::custom(Codex, "X".into(), "ftp://x.test".into(), KEY.into());
        assert!(store.add(bad).is_err());
    }

    #[test]
    fn store_round_trips_privately_and_atomically() {
        let home = tempfile::tempdir().unwrap();
        assert_eq!(Store::load(home.path()).unwrap(), Store::default());
        let mut store = Store::default();
        let id = kimi(&mut store);
        store.use_machine(Claude, &id).unwrap();
        store.use_bot("bot-1", Claude, OFFICIAL).unwrap();
        store.pin("sess-1", Claude, "g1", "bot-1", &Selection::Official(Default::default()));
        store.save(home.path()).unwrap();
        assert_eq!(Store::load(home.path()).unwrap(), store);
        let raw: serde_json::Value = serde_json::from_slice(&std::fs::read(Store::path(home.path())).unwrap()).unwrap();
        assert_eq!(raw["machine"]["claude"], id.as_str());
        assert_eq!(raw["sessions"]["sess-1"]["provider"], OFFICIAL);
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(Store::path(home.path())).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o600);
        }
        // No temp files left behind; a failed write leaves the previous file intact.
        let names: Vec<_> = std::fs::read_dir(home.path()).unwrap().map(|e| e.unwrap().file_name()).collect();
        assert_eq!(names, vec![std::ffi::OsString::from("providers.json")]);
        std::fs::create_dir(home.path().join(format!("providers.json.{}.tmp", std::process::id()))).unwrap();
        assert!(Store::default().save(home.path()).is_err());
        assert_eq!(Store::load(home.path()).unwrap(), store);
    }

    #[test]
    fn update_persists_changes_under_lock() {
        let home = tempfile::tempdir().unwrap();
        let id = Store::update(home.path(), |s| Ok(kimi(s))).unwrap();
        Store::update(home.path(), |s| s.use_machine(Claude, &id)).unwrap();
        assert_eq!(Store::load(home.path()).unwrap().machine[&Claude], id);
        assert!(Store::update(home.path(), |s| s.use_machine(Codex, &id)).is_err(), "claude provider for codex");
    }

    #[test]
    fn the_official_selection_carries_the_agents_extras() {
        let mut store = Store::default();
        let o = Official { env: BTreeMap::from([("A".into(), "1".into())]), proxy: Some("http://p.test:1".into()) };
        store.set_official(Claude, o.clone()).unwrap();
        assert_eq!(store.effective(Claude, "b").unwrap(), Selection::Official(o.clone()));
        assert_eq!(store.effective(Codex, "b").unwrap(), Selection::Official(Official::default()));
        assert_eq!(store.resolve_run(Claude, "b", Some("legacy")).unwrap(), RunPlan::Resume(Selection::Official(o)));
        let env = store.official(Claude).process_env();
        assert_eq!((env["A"].as_str(), env["HTTPS_PROXY"].as_str()), ("1", "http://p.test:1"));
        assert_eq!(env["NO_PROXY"], "localhost,127.0.0.1,::1");
        store.set_official(Claude, Official::default()).unwrap();
        assert!(store.official.is_empty(), "nothing stored for an empty one");
    }

    #[test]
    fn effective_precedence_is_bot_then_machine_then_official() {
        let mut store = Store::default();
        assert_eq!(store.effective(Claude, "b").unwrap(), Selection::Official(Default::default()));
        let a = kimi(&mut store);
        let b = kimi(&mut store);
        store.use_machine(Claude, &a).unwrap();
        assert_eq!(store.effective(Claude, "b").unwrap().key(), a);
        store.use_bot("b", Claude, &b).unwrap();
        assert_eq!(store.effective(Claude, "b").unwrap().key(), b);
        assert_eq!(store.effective(Claude, "other").unwrap().key(), a);
        store.use_bot("b", Claude, OFFICIAL).unwrap();
        assert_eq!(store.effective(Claude, "b").unwrap(), Selection::Official(Default::default()));
        store.use_bot("b", Claude, INHERIT).unwrap();
        assert_eq!(store.effective(Claude, "b").unwrap().key(), a);
        assert_eq!(store.effective(Codex, "b").unwrap(), Selection::Official(Default::default()));
        assert!(store.use_bot("b", Codex, &a).is_err(), "override must match the bot's agent");
        assert!(store.use_machine(Claude, "nope").is_err());
    }

    #[test]
    fn session_pin_survives_default_changes() {
        let mut store = Store::default();
        let a = kimi(&mut store);
        let b = kimi(&mut store);
        store.use_machine(Claude, &a).unwrap();
        let RunPlan::New { selection, provider_removed: false } = store.resolve_run(Claude, "bot", None).unwrap()
        else {
            panic!("new session expected")
        };
        store.pin("s1", Claude, "g", "bot", &selection);
        store.use_machine(Claude, &b).unwrap();
        store.use_bot("bot", Claude, OFFICIAL).unwrap();
        let RunPlan::Resume(Selection::Provider(p)) = store.resolve_run(Claude, "bot", Some("s1")).unwrap() else {
            panic!("resume with the pinned provider expected")
        };
        assert_eq!(p.id, a);
        // Editing the pinned provider keeps the pin; the run sees the new revision.
        store.edit(&a, |p| p.api_key = "sk-rotated-000000000000".into()).unwrap();
        let RunPlan::Resume(Selection::Provider(p)) = store.resolve_run(Claude, "bot", Some("s1")).unwrap() else {
            panic!()
        };
        assert_eq!(p.revision, 2);
        assert_eq!(
            store.resolve_run(Claude, "bot", Some("legacy")).unwrap(),
            RunPlan::Resume(Selection::Official(Default::default()))
        );
        let stale = store.stale().unwrap();
        assert_eq!(stale.len(), 1);
        assert_eq!((stale[0].session.as_str(), stale[0].effective.as_str()), ("Kimi For Coding", OFFICIAL_NAME));
        store.pin("s2", Claude, "g", "bot", &Selection::Official(Default::default()));
        store.sessions.get_mut("s2").unwrap().pinned_at += 1;
        assert!(store.stale().unwrap().is_empty(), "only the latest session of a (group, bot) counts");
    }

    #[test]
    fn removing_a_pinned_provider_starts_a_new_session() {
        let mut store = Store::default();
        let a = kimi(&mut store);
        store.use_machine(Claude, &a).unwrap();
        store.use_bot("bot", Claude, &a).unwrap();
        store.pin("s1", Claude, "g", "bot", &store.effective(Claude, "bot").unwrap());
        store.remove(&a).unwrap();
        assert!(store.machine.is_empty() && store.bots.is_empty());
        assert_eq!(
            store.resolve_run(Claude, "bot", Some("s1")).unwrap(),
            RunPlan::New { selection: Selection::Official(Default::default()), provider_removed: true }
        );
        assert!(store.stale().unwrap().is_empty());
        assert!(store.remove(&a).is_err());
    }

    #[test]
    fn edit_bumps_revision_only_on_change() {
        let mut store = Store::default();
        let a = kimi(&mut store);
        store.edit(&a, |_| {}).unwrap();
        assert_eq!(store.get(&a).unwrap().revision, 1);
        store.edit(&a, |p| p.model = Some("k3".into())).unwrap();
        assert_eq!(store.get(&a).unwrap().revision, 2);
        assert!(store.edit(&a, |p| p.base_url = "nope".into()).is_err());
        assert_eq!(store.get(&a).unwrap().revision, 2);
    }

    #[test]
    fn upsert_dedupes_by_source_then_connection() {
        let mut store = Store::default();
        let mut p = Provider::custom(Codex, "A".into(), "https://a.test/v1/".into(), KEY.into());
        p.source = Some(Source { kind: SourceKind::CcSwitch, id: Some("cc-1".into()) });
        let id = store.upsert(p.clone()).unwrap();
        assert_eq!(store.upsert(p.clone()).unwrap(), id);
        assert_eq!(store.get(&id).unwrap().revision, 1, "unchanged import keeps the revision");
        p.base_url = "https://b.test/v1".into();
        assert_eq!(store.upsert(p.clone()).unwrap(), id, "same source id");
        assert_eq!(store.get(&id).unwrap().revision, 2);
        let manual = Provider::custom(Codex, "B".into(), "https://b.test/v1/".into(), KEY.into());
        assert_eq!(store.upsert(manual).unwrap(), id, "same agent + base URL + key");
        assert_eq!(store.get(&id).unwrap().revision, 3);
        let other = Provider::custom(Codex, "C".into(), "https://b.test/v1".into(), "sk-another-key-xxxx".into());
        assert_ne!(store.upsert(other).unwrap(), id);
        assert_eq!(store.providers.len(), 2);
    }

    #[test]
    fn view_never_contains_the_key() {
        let mut store = Store::default();
        let a = kimi(&mut store);
        let view = store.view();
        let json = serde_json::to_string(&view).unwrap();
        assert!(!json.contains(KEY) && !json.contains("0123456789"));
        assert_eq!(view.providers[0].api_key, "****abcd");
        assert_eq!(view.providers[0].id, a);
        assert_eq!(mask_key("sk-12345"), "****");
        assert_eq!(mask_key("密钥密钥密钥密钥密钥"), "****密钥密钥");
    }

    #[test]
    fn view_masks_the_proxy_password() {
        let mut store = Store::default();
        let id = kimi(&mut store);
        store.edit(&id, |p| p.proxy = Some("http://bob:s3cret@10.0.0.2:3128".into())).unwrap();
        let view = store.view();
        assert_eq!(view.providers[0].proxy.as_deref(), Some("http://bob:****@10.0.0.2:3128"));
        assert!(!serde_json::to_string(&view).unwrap().contains("s3cret"));
        assert_eq!(mask_proxy("http://127.0.0.1:7890"), "http://127.0.0.1:7890");
    }
}
