export default {
  管理后台: 'Admin console',
  共工空间: 'Gonggong Space',
  返回消息: 'Back to messages',
  即将上线: 'Coming soon',
  '该页面正在开发中。': 'This page is under construction.',
  全部: 'All',
  审批: 'Approvals',
  锁与同步: 'Lock & sync',
  管理: 'Admin',
  运行: 'Runs',
  系统: 'System',
  审计记录: 'Audit log',
  完成: 'Done',
  类型: 'Type',
  操作人: 'Actor',
  摘要: 'Summary',
  详情: 'Details',
  '审批、提问、锁与同步事件、管理员操作，永久保存。':
    'Approvals, questions, lock and sync events, and admin actions, kept permanently.',
  '已载入 {n} 条': '{n} loaded',
  搜索审计记录: 'Search audit log',
  '搜索摘要、群或操作人': 'Search summary, group or actor',
  全部操作人: 'All actors',
  审计记录列表: 'Audit log entries',
  没有匹配的记录: 'No matching entries',
  暂无记录: 'No entries yet',
  时间: 'Time',
  加载更多: 'Load more',
  已归档: 'Archived',
  归档: 'Archived',
  '归档 · {n} 天后清除': 'Archived · purged in {n} {n:day|days}',
  '所有群的模式、仓库与存档状态。': 'Mode, repo and archive state of every group.',
  '{n} 个群': '{n} {n:group|groups}',
  搜索群或仓库: 'Search groups or repos',
  群列表: 'Groups',
  没有匹配的群: 'No matching groups',
  还没有群: 'No groups yet',
  模式: 'Mode',
  未绑定: 'Not set',
  成员: 'Members',
  存档: 'Archive',
  从未连接: 'Never connected',
  '测量于 {time}': 'Measured {time}',
  机器与网络: 'Machines & network',
  '所有机器的系统、硬件、daemon 版本、在线状态与网络质量记录。':
    'OS, hardware, daemon version, online status and network quality of every machine.',
  '{n} 台 · {online} 台在线': '{n} {n:machine|machines} · {online} online',
  '机器详情…': 'Machine details…',
  搜索机器或主人: 'Search machines or owners',
  机器列表: 'Machines',
  '吊销机器…': 'Revoke machine…',
  没有匹配的机器: 'No matching machines',
  还没有机器: 'No machines yet',
  主人: 'Owner',
  '机器#nav': 'Machines',
  硬件: 'Hardware',
  'Agent 版本': 'Agent versions',
  '最新版本 {version} · {source}': 'Latest {version} · {source}',
  可升级: 'Update available',
  延迟: 'Latency',
  带宽: 'Bandwidth',
  状态: 'Status',
  在线: 'Online',
  离线: 'Offline',
  最后心跳: 'Last heartbeat',
  '{n} 台 daemon 协议版本过旧': '{n} {n:daemon|daemons} on an outdated protocol',
  '{list}，服务器已拒绝连接并提示升级。':
    '{list}. The server rejected the connection and asked for an upgrade.',
  '{name} 运行 v{version}（协议 v{protocol}）': '{name} runs v{version} (protocol v{protocol})',
  '、': ', ',
  '网络质量由成员在 daemon 中测量上报（gg net 或桌面端「测量延迟与带宽」），不在群里展示。强制同步开启阈值：延迟 ≤ {latency} ms，带宽 ≥ {bandwidth} Mbps。':
    'Members measure network quality in the daemon (gg net or "Measure latency & bandwidth" in the desktop app); it is not shown in groups. Force sync requires latency ≤ {latency} ms and bandwidth ≥ {bandwidth} Mbps.',
  '网络质量由成员在 daemon 中测量上报（gg net 或桌面端「测量延迟与带宽」），不在群里展示。':
    'Members measure network quality in the daemon (gg net or "Measure latency & bandwidth" in the desktop app); it is not shown in groups.',
  账号与角色: 'Accounts & roles',
  '创建账号、分配角色、重置密码；停用会立即断开该成员的所有机器与登录。':
    "Create accounts, assign roles and reset passwords. Disabling immediately disconnects all of the member's machines and sessions.",
  '所有群的模式、仓库与权威副本状态。': 'Mode, repo and authoritative copy state of every group.',
  配置: 'Configuration',
  系统参数: 'System parameters',
  '平台默认值；团队管理员可在团队设置中覆盖部分参数，群管理员再在群设置中调整群级参数。':
    'Platform defaults; team admins override some of them in team settings, and group admins adjust group-level params in group settings.',
  客户端发布: 'Client releases',
  '成员机器上的 daemon 连上后自动升级到这里的版本；gg-cast 在首次推送实时画面时按需下载。':
    "Daemons on members' machines upgrade to this version when they connect; gg-cast downloads on demand the first time a live view is streamed.",
  观测: 'Observability',
  用量: 'Usage',
  '公开链接#nav': 'Public links',
  'Bot 预览的外部公开链接：到期或收回后立即失效，访问记入审计。':
    'Public links to Bot previews: they stop working once expired or revoked, and every visit is audited.',
  同步与锁: 'Sync & lock',
  运行与会话: 'Runs & sessions',
  '附件#nav': 'Attachments',
  机器连接: 'Machine connections',
  数据保留: 'Data retention',
  '群与 Bot 默认值': 'Group & Bot defaults',
  其他: 'Other',
  已开放自助注册: 'Self sign-up enabled',
  已关闭自助注册: 'Self sign-up disabled',
  '系统参数已保存，已写入审计记录': 'System parameters saved and recorded in the audit log',
  账号: 'Account',
  开放自助注册: 'Allow self sign-up',
  '开启后登录页显示注册入口，注册即成为普通成员；关闭后只能由管理员创建账号。':
    'When on, the login page offers sign-up and new accounts become members; when off, only admins can create accounts.',
  已开放: 'On',
  '已关闭#off': 'Off',
  已修改: 'Modified',
  未保存的修改: 'Unsaved changes',
  '已修改 {n} 项': '{n} {n:change|changes}',
  放弃: 'Discard',
  保存: 'Save',
  未发布: 'Not released',
  已发布: 'Released',
  '不是发布产物，文件名应形如 gonggong-0.2.0-macos-aarch64':
    'Not a release artifact; the file name should look like gonggong-0.2.0-macos-aarch64',
  '已移除 {kind}（{platform}）': 'Removed {kind} ({platform})',
  '当前版本 {version}': 'Current version {version}',
  尚未发布: 'Not released yet',
  拖入发布产物: 'Drop release artifacts',
  '运行 scripts/release.sh 后，把 dist/<版本>/ 里的 gonggong-* 与 gg-cast-* 文件拖到这里。文件名决定平台与版本；更高的版本会替换整个发布。':
    'After running scripts/release.sh, drop the gonggong-* and gg-cast-* files from dist/<version>/ here. File names determine platform and version; a higher version replaces the whole release.',
  各平台发布文件: 'Release files by platform',
  平台: 'Platform',
  标识: 'ID',
  'gg-cast（实时画面）': 'gg-cast (live view)',
  '移除 {kind}…': 'Remove {kind}…',
  '要移除 {platform} 的 {kind} 吗？': 'Remove {kind} for {platform}?',
  '该平台的机器将不再自动升级，直到重新上传。':
    'Machines on this platform stop auto-upgrading until it is uploaded again.',
  '该平台的机器将无法推送实时画面，直到重新上传。':
    'Machines on this platform cannot stream a live view until it is uploaded again.',
  取消: 'Cancel',
  移除: 'Remove',
  已停用: 'Disabled',
  待修改密码: 'Password change pending',
  正常: 'Active',
  '{n} 台 · {state}': '{n} · {state}',
  '至少 {n} 位': 'At least {n} characters',
  重新生成: 'Regenerate',
  '已启用 {name}，需重新绑定机器': 'Enabled {name}; machines must be bound again',
  '{n} 个账号': '{n} {n:account|accounts}',
  '新建账号…': 'New account…',
  搜索姓名或账号: 'Search name or account',
  账号列表: 'Accounts',
  '编辑…': 'Edit…',
  启用: 'Enable',
  '重置密码…': 'Reset password…',
  '停用…': 'Disable…',
  没有匹配的成员: 'No matching members',
  还没有账号: 'No accounts yet',
  角色: 'Role',
  还没有其他成员: 'No other members yet',
  '新建账号后，把账号和初始密码发给同事；对方首次登录时会被要求修改密码。':
    "After creating an account, send the account and initial password to your colleague; they'll be asked to change it on first login.",
  '要停用账号 {name} 吗？': 'Disable account {name}?',
  '可以随时重新启用，但需要重新绑定机器。':
    'You can re-enable it at any time, but machines must be bound again.',
  '立即吊销其所有 daemon token 和 Web 会话': 'Immediately revokes all their daemon tokens and web sessions',
  'daemon 下次连接失败后清除团队密钥和托管工作区（尽力而非保证）':
    'The daemon wipes team keys and managed workspaces after its next failed connection (best effort, not guaranteed)',
  '其 Bot 从所有群移除；持锁中的 Bot 按非主动中断处理':
    'Their Bots are removed from every group; a Bot holding the lock is treated as interrupted',
  群消息与审计记录保留: 'Group messages and audit records are kept',
  停用: 'Disable',
  '已停用 {name}': 'Disabled {name}',
  '临时密码至少 {n} 位': 'Temporary password must be at least {n} characters',
  '已重置，临时密码已复制，请私下发给 {name}':
    'Reset. Temporary password copied; send it to {name} privately',
  '已重置 {name} 的密码，请记下临时密码 {password}':
    "Reset {name}'s password. Note down the temporary password {password}",
  '重置 {name} 的密码': "Reset {name}'s password",
  '对方所有网页登录立即失效，需用临时密码重新登录并马上修改；已绑定的机器与 Bot 不受影响。':
    'All their web sessions end immediately; they must log in with the temporary password and change it right away. Bound machines and Bots are unaffected.',
  重置并复制: 'Reset & copy',
  临时密码: 'Temporary password',
  '重置后自动复制，请私下发给对方。': 'Copied automatically after reset; send it to them privately.',
  '账号需为 2–32 位小写字母、数字或 . _ -': 'Account must be 2–32 lowercase letters, digits or . _ -',
  '初始密码至少 {n} 位': 'Initial password must be at least {n} characters',
  '账号 {account}  初始密码 {password}': 'Account {account}  Initial password {password}',
  '已创建账号 {account}，账号和初始密码已复制，首次登录需修改密码':
    'Created account {account}. Account and initial password copied; the password must be changed on first login',
  '已创建账号 {account}，首次登录需修改密码':
    'Created account {account}. The password must be changed on first login',
  '编辑成员 {name}': 'Edit member {name}',
  新建成员: 'New member',
  首次登录需修改初始密码: 'The initial password must be changed on first login',
  创建: 'Create',
  '2–32 位小写字母、数字或 . _ -，创建后不能修改':
    "2–32 lowercase letters, digits or . _ -; can't be changed later",
  姓名: 'Name',
  王磊: 'Wang Lei',
  不能修改自己的角色: "You can't change your own role",
  初始密码: 'Initial password',
  '创建后账号与初始密码会一起复制。': 'The account and initial password are copied together after creation.',
  '机器#count': 'Machines',
  'Bot#nav': 'Bots',
  团队: 'Team',
  '团队#nav': 'Teams',
  全部团队: 'All teams',
  所属团队: 'Teams',
  单团队模式: 'Single-team mode',
  '开启后不显示团队切换，新账号自动加入唯一的团队；仅在恰好有一个未归档团队时可开启。':
    'Hides team switching and puts new accounts in the only team; can be turned on only when exactly one live team exists.',
  已开启: 'On',
  已开启单团队模式: 'Single-team mode turned on',
  演示: 'Demo',
  演示模式: 'Demo mode',
  '对外公开演示时开启，防止内容经内网穿透的域名流到互联网、访客破坏演示环境：预览只能登录后在群内查看，不能创建公开链接，已发出的公开链接立即失效，预览卡片不同步到飞书；实时画面只能观看不能操控；Bot 不能使用「完全访问」档位，已设为完全访问的按「工作区写入」运行；除系统管理员外不能改密码和昵称，不能解散群、移除成员、删除 Bot、吊销机器、归档团队。':
    'Turn on for public demos, so content cannot leak to the internet through tunnel domains and visitors cannot break the demo: previews can only be viewed in their group after signing in, public links cannot be created and existing ones stop working at once, preview cards are not sent to Feishu; live views are watch-only; bots cannot use the Full access tier, and those set to it run at Workspace write; apart from system admins, nobody can change passwords or nicknames, dissolve groups, remove members, delete bots, revoke machines or archive teams.',
  已开启演示模式: 'Demo mode turned on',
  已关闭演示模式: 'Demo mode turned off',
  已关闭单团队模式: 'Single-team mode turned off',
  建团队权限: 'Who can create teams',
  '单团队模式下任何人都不能新建团队。': 'Nobody can create teams in single-team mode.',
  建团队权限已保存: 'Team creation setting saved',
  所有人: 'Everyone',
  仅系统管理员: 'System admins only',
  '全部团队的所有者、成员数与状态；团队内的成员、邀请与配置由团队管理员在团队设置中管理。':
    "Every team's owner, member count and status; members, invites and settings inside a team are managed by its admins in team settings.",
  '{n} 个团队': '{n} {n:team|teams}',
  '新建团队…': 'New team…',
  搜索团队或所有者: 'Search teams or owners',
  团队列表: 'Teams',
  '指定所有者…': 'Set owner…',
  恢复团队: 'Restore team',
  没有匹配的团队: 'No matching teams',
  创建时间: 'Created',
  已恢复团队: 'Team restored',
  已指定所有者: 'Owner set',
  团队已创建: 'Team created',
  '指定「{name}」的所有者': 'Set the owner of "{name}"',
  '对方成为所有者（未加入则自动加入）；原所有者改为管理员。':
    'They become an owner (joining if needed); the previous owners become admins.',
  选择账号: 'Choose an account',
  '各群与私聊的定时任务，可停用或删除任意任务。':
    'Scheduled tasks of every group and direct chat; turn off or delete any of them.',
  '各群与私聊的定时任务：到点由候选 Bot 中第一个可用的执行。可在此停用或删除任意任务。':
    'Scheduled tasks of every group and direct chat: the first available candidate Bot runs each. Turn off or delete any of them here.',
  '{n} 个任务': '{n} {n:task|tasks}',
  '{owner} 的私聊': "{owner}'s direct chat",
  '搜索任务、群或 Bot': 'Search tasks, groups or Bots',
  '24 小时内触发': 'Fired in 24 h',
  '24 小时内失败': 'Failed in 24 h',
  已自动停用: 'Turned off automatically',
  定时任务列表: 'Scheduled tasks',
  没有匹配的任务: 'No matching tasks',
  任务: 'Task',
}
