export default {
  '检查失败，请稍后重试': 'Check failed. Try again later',
  '正在检查访问…': 'Checking access…',
  仓库: 'Repository',
  重新检查: 'Recheck',
  选择仓库: 'Choose repository',
  '不绑定 · 各 Bot 使用本机目录': 'None · Each Bot uses a folder on its machine',
  基准分支: 'Base branch',
  '{n} 个群在用': 'Used by {n} {n:group|groups}',
  本机已有: 'On this machine',
  加载失败: 'Failed to load',
  '使用地址 {url}': 'Use URL {url}',
  最近: 'Recent',
  搜索仓库: 'Search repositories',
  '搜索仓库，或粘贴地址': 'Search repositories or paste a URL',
  私有: 'Private',
  重试: 'Retry',
  没有匹配的仓库: 'No matching repositories',
  '连接 GitHub / GitLab 账号…': 'Connect a GitHub / GitLab account…',
  不绑定仓库: 'No repository',
  无权限: 'No permission',
  网络或证书: 'Network or certificate',
  超时: 'Timed out',
  未选择工作区: 'No workspace chosen',
  '已暂停 · {reason}': 'Paused · {reason}',
  '托管克隆 · 就绪': 'Managed clone · Ready',
  '克隆中…': 'Cloning…',
  等待上线: 'Waiting to come online',
  失败: 'Failed',
  '已更换仓库 · 各 Bot 的托管工作区将重建':
    "Repository changed · Each Bot's managed workspace will be rebuilt",
  已绑定仓库: 'Repository bound',
  '正在让 {name} 的机器重新 clone…': "Asking {name}'s machine to clone again…",
  '未绑定 · 各 Bot 使用本机目录': 'Not bound · Each Bot uses a folder on its machine',
  '更换…': 'Change…',
  '绑定仓库…': 'Bind repository…',
  '各 Bot 的托管工作区将重建': "Each Bot's managed workspace will be rebuilt",
  取消: 'Cancel',
  '检查中…': 'Checking…',
  更换仓库: 'Change repository',
  绑定仓库: 'Bind repository',
  '各 Bot 的工作区': 'Bot workspaces',
  '离线，上线后可更改': 'Offline; can be changed once online',
  '更改…': 'Change…',
  '本群还没有 Bot': 'No Bots in this group yet',
  可访问: 'Accessible',
  '无权限 · 进群后暂停': 'No permission · Paused after joining',
  '网络或证书 · 进群后暂停': 'Network or certificate · Paused after joining',
  '超时 · 进群后暂停': 'Timed out · Paused after joining',
  '分支不存在#status': 'Branch not found',
  '离线 · 上线后验证': 'Offline · Checked once online',
  '没有可检查的 Bot · 进群后由各 Bot 的机器验证':
    "No Bots to check · Each Bot's machine checks after joining",
  '分支 {branch} 不存在': 'Branch {branch} not found',
  '{n} 个 Bot 可访问': '{n} {n:Bot|Bots} can access',
  '{n} 个进群后暂停': '{n} paused after joining',
  '{n} 个离线': '{n} offline',
} satisfies Record<string, string>
