export default {
  接入链接: 'Connect link',
  '一次性接入链接 · {time} 后失效': 'One-time connect link · Expires in {time}',
  接入链接已失效: 'Connect link expired',
  重新生成: 'Regenerate',
  在客户端中打开: 'Open in client',
  已复制接入链接: 'Connect link copied',
  复制接入链接: 'Copy connect link',
  '没有自动打开？复制接入链接，粘贴到客户端。':
    "Didn't open automatically? Copy the connect link and paste it into the client.",
  重试: 'Retry',
  使用命令行: 'Use the command line',
  复制命令: 'Copy command',
  已复制绑定命令: 'Bind command copied',
  '没有安装客户端时，在机器的终端里执行。':
    "Without the client installed, run this in the machine's terminal.",
  生成接入链接: 'Generate connect link',
  客户端绑定: 'Client binds',
  '上报机器与 agent': 'Machine and agents reported',
  绑定新机器: 'Bind new machine',
  '在共工空间客户端中打开接入链接，确认后这台机器就归属于你，Bot 在上面运行。':
    'Open the connect link in the Gonggong Space client. Once confirmed, the machine is yours and Bots run on it.',
  完成: 'Done',
  取消: 'Cancel',
  '等待客户端确认绑定…': 'Waiting for the client to confirm…',
  '绑定后该机器归属于你，客户端会上报机器名、系统、CPU、内存与本机可用的 Claude Code / Codex；同一台机器重新绑定会恢复原记录。还没安装共工空间客户端？':
    'Once bound, the machine is yours. The client reports its name, OS, CPU, memory and available Claude Code / Codex; rebinding the same machine restores its record. No Gonggong Space client yet?',
  'macOS（Apple 芯片）': 'macOS (Apple silicon)',
  'macOS（Intel）': 'macOS (Intel)',
  'Linux {arch}（命令行）': 'Linux {arch} (CLI)',
  '前往 GitHub 下载': 'Download from GitHub',
  已恢复原有机器: 'Existing machine restored',
  绑定成功: 'Bound',
  '{name} 之前绑定过，已沿用原机器记录与其上的 Bot（{os} · {arch}）':
    '{name} was bound before; its record and Bots are kept ({os} · {arch})',
  '本机已归属你 · {name}（{os} · {arch}）': 'This machine is now yours · {name} ({os} · {arch})',
  '本机 agent': 'Agents on this machine',
  未安装: 'Not installed',
  '未检测到 Claude Code / Codex，安装后在客户端中重新检测即可上报。':
    'No Claude Code / Codex detected. Install one, then re-detect in the client to report it.',
  '等待上报 agent…在机器上打开共工空间客户端':
    'Waiting for agents… Open the Gonggong Space client on the machine',
  '你自己创建的 Bot 已直接绑定到本机，无需操作；管理员为你创建并指定到本机的 Bot，需在通知中确认后才能被触发。':
    'Bots you created are bound to this machine directly. Bots an admin created for you on this machine need your confirmation in notifications before they can be triggered.',
  '{n} 核': '{n} {n:core|cores}',
  'Agent 工具': 'Agent tools',
  '供应商#nav': 'Providers',
  '机器离线，上线后才能管理 Agent 工具与供应商':
    'The machine is offline; manage agent tools and providers once it is online',
  '请先升级该机器的 daemon，才能管理{what}': "Upgrade this machine's daemon first to manage {what}",
  与: ' and ',
  '已重命名为 {name}': 'Renamed to {name}',
  内存: 'Memory',
  内核: 'Kernel',
  'MAC 地址': 'MAC address',
  机器详情: 'Machine details',
  吊销机器: 'Revoke machine',
  概览: 'Overview',
  机器离线: 'Machine offline',
  '请先升级该机器的 daemon': "Upgrade this machine's daemon first",
  '供应商与 Agent 工具只保存在机器上，机器上线后才能查看和修改。':
    'Providers and agent tools live only on the machine; view and edit them once it is online.',
  '当前 daemon 版本不支持在 Web 上管理，升级后即可使用。':
    "This daemon version can't be managed from the web; upgrade to use this.",
  在线: 'Online',
  离线: 'Offline',
  名称: 'Name',
  '留空则使用主机名。': 'Leave empty to use the hostname.',
  保存: 'Save',
  已安装: 'Installed',
  '未检测到 Agent': 'No agents detected',
  '运行的 Bot': 'Bots running here',
  主人: 'Owner',
  最后在线: 'Last online',
  首次绑定: 'First bound',
  最近绑定: 'Last bound',
  国内厂商: 'China',
  聚合平台: 'Aggregators',
  海外: 'International',
  '额外环境变量每行一个 KEY=VALUE：{line}': 'Extra environment variables take one KEY=VALUE per line: {line}',
  请填写名称: 'Enter a name',
  '请填写 Base URL': 'Enter a Base URL',
  '请填写 API Key': 'Enter an API key',
  编辑供应商: 'Edit provider',
  '新增 {agent} 供应商': 'Add {agent} provider',
  '选择厂商，之后只需填写 API Key': 'Choose a vendor; then just enter the API key',
  恢复为预设值: 'Restore preset values',
  厂商: 'Vendor',
  自定义: 'Custom',
  '更换…': 'Change…',
  '留空则保留已保存的 Key': 'Leave empty to keep the saved key',
  'Key 只保存在这台机器上': 'The key is stored only on this machine',
  必填: 'Required',
  '获取 Key': 'Get a key',
  模型: 'Model',
  '可从列表选择，也可直接输入': 'Choose from the list or type one',
  默认: 'Default',
  设为本机默认: 'Set as machine default',
  高级: 'Advanced',
  '{tier} 模型': '{tier} model',
  额外环境变量: 'Extra environment variables',
  '每行一个 KEY=VALUE': 'One KEY=VALUE per line',
  搜索厂商: 'Search vendors',
  '手动填写 Base URL': 'Enter the Base URL manually',
  '从 CC Switch 导入 {agent} 供应商': 'Import {agent} providers from CC Switch',
  '只读取这台机器上的 CC Switch，Key 只保存在这台机器上':
    'Reads only CC Switch on this machine; keys are stored only on this machine',
  导入: 'Import',
  'CC Switch 里没有可直接使用的 {agent} 供应商': 'CC Switch has no usable {agent} providers',
  'CC Switch 当前': 'Current in CC Switch',
  将更新已有项: 'Updates existing',
  '将 CC Switch 当前使用的设为本机默认': "Set CC Switch's current provider as machine default",
  粘贴链接导入: 'Import from link',
  'CC Switch 的供应商分享链接，Key 只保存在这台机器上':
    'A CC Switch provider share link; the key is stored only on this machine',
  导入链接: 'Import link',
  '{agent} 的本机默认已切换，新会话生效': '{agent} machine default switched; applies to new sessions',
  '{agent} 供应商': '{agent} providers',
  '已删除供应商 {name}': 'Deleted provider {name}',
  '它是本机默认，删除后本机默认改为官方登录。':
    'It is the machine default; after deletion the default becomes the official login.',
  '单独设置为它的 Bot 改为继承本机默认。': 'Bots set to it will inherit the machine default.',
  '选中的是本机默认，新会话使用它；进行中的会话开启新会话后才切换':
    'The selected one is the machine default for new sessions; ongoing sessions switch once a new session starts',
  '使用这台机器上 CLI 自己的登录与配置': "Uses the CLI's own login and config on this machine",
  '编辑…': 'Edit…',
  删除: 'Delete',
  '从 CC Switch 导入…': 'Import from CC Switch…',
  '粘贴链接导入…': 'Import from link…',
  '新增…': 'Add…',
  供应商已保存: 'Provider saved',
  '已从 CC Switch 导入 {n} 个供应商': 'Imported {n} {n:provider|providers} from CC Switch',
  '已导入供应商 {name}': 'Imported provider {name}',
  '要删除供应商 {name} 吗？': 'Delete provider {name}?',
  '要吊销机器 {name} 吗？': 'Revoke machine {name}?',
  '吊销后需要重新生成接入链接才能再次使用。': 'After revoking, a new connect link is needed to use it again.',
  '该机器的 daemon 立即断开': "The machine's daemon disconnects immediately",
  'daemon 会清理本机托管工作区；/cd 目录与备份保留':
    'The daemon removes managed workspaces; /cd folders and backups are kept',
  吊销: 'Revoke',
  '已吊销 {name}': 'Revoked {name}',
  '运行 ACP 适配器，托管安装 Claude Code / Codex 也用它（需 ≥ {min}）':
    'Runs the ACP adapter and managed Claude Code / Codex installs (requires ≥ {min})',
  '淘宝镜像（npmmirror）': 'Taobao mirror (npmmirror)',
  官方源: 'Official registry',
  镜像源已保存: 'Mirror saved',
  来源: 'Source',
  共工空间托管: 'Managed by Gonggong Space',
  自行安装: 'Self-installed',
  最新版本: 'Latest version',
  '无法获取，请检查镜像源': 'Unavailable; check the mirror',
  有更新: 'Update available',
  '版本过低 {version}': 'Too old {version}',
  '已安装 {version}': 'Installed {version}',
  安装: 'Install',
  '升级到 {version}': 'Upgrade to {version}',
  升级命令: 'Upgrade command',
  自行安装的版本由你在本机终端升级: 'Run it in a terminal on this machine to upgrade your own install',
  '正在安装…': 'Installing…',
  安装失败: 'Install failed',
  安装完成: 'Installed',
  安装日志: 'Install log',
  '等待机器输出…': 'Waiting for machine output…',
  镜像源: 'Mirror',
  '安装、升级 Node.js、Claude Code 与 Codex 时从这里下载':
    'Node.js, Claude Code and Codex installs and upgrades download from here',
  'Node.js 下载地址': 'Node.js download URL',
  'index.json 所在的目录': 'The folder containing index.json',
  官方登录: 'Official login',
  已删除的供应商: 'Deleted provider',
  其他群: 'Other group',
  '{group}（{bot}）': '{group} ({bot})',
  '{n} 个群的会话仍在使用 {from}，开启新会话后才会切换到 {to}':
    'Sessions in {n} {n:group|groups} still use {from} and switch to {to} once a new session starts',
  '{n} 个群的会话正在使用 {name}，删除后它们下一轮会自动开启新会话':
    'Sessions in {n} {n:group|groups} use {name}; after deletion their next run starts a new session',
  '{text}：': '{text}:',
  '要让新会话改用 {name} 吗？': 'Switch new sessions to {name}?',
  '进行中的会话不受影响，在群里开启新会话后才会切换。':
    'Ongoing sessions are unaffected and switch once a new session starts in the group.',
  切换: 'Switch',
} satisfies Record<string, string>
