export default {
  关闭预览并停止应用: 'Close preview and stop the app',
  关闭预览: 'Close preview',
  停止穿透和服务: 'Stop tunnel and service',
  停止穿透: 'Stop tunnel',
  打开: 'Open',
  在工作台打开: 'Open in workbench',
  启动服务: 'Start service',
  公开链接: 'Public link',
  重新截图: 'Retake screenshot',
  '正在重试…': 'Retrying…',
  '{n} 秒后自动重试': 'Retrying in {n}s',
  立即重试: 'Retry now',
  '{n} 天': '{n} {n:day|days}',
  已收回: 'Revoked',
  有效: 'Active',
  已过期: 'Expired',
  预览已关闭: 'Preview closed',
  已复制公开链接: 'Public link copied',
  '复制失败，请手动选择链接': 'Copy failed. Select the link manually.',
  '公开链接 · {title}': 'Public link · {title}',
  '拿到链接的人无需登录即可访问这个预览，到期或收回后立即失效；访问会记入审计。':
    'Anyone with the link can view this preview without signing in. It stops working once it expires or is revoked; visits are audited.',
  有效期: 'Expires in',
  生成链接: 'Create link',
  复制: 'Copy',
  '{name} 生成 · {expires} 到期 · 访问 {n} 次':
    'Created by {name} · expires {expires} · {n} {n:visit|visits}',
  收回: 'Revoke',
  'Bot 预览的外部公开链接：拿到链接的人无需登录即可访问，到期或收回后立即失效。':
    'Public links to Bot previews: anyone with the link can view without signing in; links stop working once they expire or are revoked.',
  '{n} 条 · {active} 条有效': '{n} total · {active} active',
  '搜索预览、群或创建人': 'Search previews, groups or creators',
  公开链接列表: 'Public links',
  '延长 7 天': 'Extend 7 days',
  没有匹配的公开链接: 'No matching public links',
  还没有公开链接: 'No public links yet',
  创建人: 'Created by',
  到期: 'Expires',
  访问: 'Visits',
  '{n} 次': '{n}',
  状态: 'Status',
  '共工空间桌面端「实时画面」页': 'the Live view page of the Gonggong Space desktop app',
  无法连接实时画面: "Can't connect to the live view",
  机器离线: 'Machine offline',
  应用已停止: 'App stopped',
  机器未授权屏幕录制: 'Screen recording not allowed on the machine',
  '请 Bot 主人在{page}完成授权': "Ask the Bot's owner to grant it on {page}",
  没有推送画面: 'No picture is being sent',
  'Bot 主人可在{page}查看': "The Bot's owner can check {page}",
  '机器未授权辅助功能，远程操作不会生效，请在{page}完成授权':
    "Accessibility isn't allowed on the machine, so remote input won't work. Grant it on {page}",
  网络差: 'Poor network',
  网络一般: 'Fair network',
  帧率: 'Frame rate',
  画质: 'Quality',
  隐藏画面数据: 'Hide stream stats',
  显示画面数据: 'Show stream stats',
  '请 Bot 主人在运行 Bot 的电脑上操作': "Ask the Bot's owner to do this on the computer running the Bot",
  正在启动实时画面: 'Starting live view',
  '正在启动实时画面…': 'Starting live view…',
  '网络较差，建议切换到「{quality}」': 'Poor network; try switching to "{quality}"',
  '{title} 实时画面': '{title} live view',
  键盘输入: 'Keyboard input',
  机器网络差: "Machine's network is poor",
  你的网络差: 'Your network is poor',
  '丢包 {loss}%': 'Loss {loss}%',
  '延迟 {rtt} ms': 'Latency {rtt} ms',
  '抖动 {jitter} ms': 'Jitter {jitter} ms',
  画面数据: 'Stream stats',
  请开启微信开发者工具的服务端口: 'Turn on the service port in WeChat DevTools',
  打开微信开发者工具: 'Open WeChat DevTools',
  '菜单栏「设置 → 安全设置」': 'From the menu bar, open "Settings → Security"',
  '打开「服务端口」': 'Turn on "Service port"',
  请在微信开发者工具里允许共工空间访问: 'Allow Gonggong Space access in WeChat DevTools',
  切换到微信开发者工具: 'Switch to WeChat DevTools',
  '在「Gonggong」授权弹窗中点击「允许」': 'Click "Allow" in the "Gonggong" authorization dialog',
  请在微信开发者工具里信任此项目: 'Trust this project in WeChat DevTools',
  '在「您信任此项目的作者吗？」弹窗中点击「信任并运行」':
    'Click "Trust and run" in the "Do you trust the author of this project?" dialog',
  '若没有弹窗，请查看开发者工具的编译输出': 'If no dialog appears, check the DevTools compile output',
  正在等待: 'Waiting',
  完成后自动继续: 'Continues automatically when done',
  设置: 'Settings',
  通用: 'General',
  外观: 'Appearance',
  安全设置: 'Security',
  代理: 'Proxy',
  服务端口: 'Service port',
  'CLI 访问令牌': 'CLI access token',
  '「Gonggong」请求访问微信开发者工具': '"Gonggong" wants to access WeChat DevTools',
  '您信任此项目的作者吗？': 'Do you trust the author of this project?',
  拒绝: 'Deny',
  取消: 'Cancel',
  允许: 'Allow',
  信任并运行: 'Trust and run',
  正在打开微信开发者工具: 'Opening WeChat DevTools',
  '正在打开微信开发者工具…': 'Opening WeChat DevTools…',
  '启动开发者工具并编译小程序，首次可能需要几十秒':
    'Starting DevTools and compiling the mini program; the first time can take tens of seconds',
  '{title} 模拟器': '{title} simulator',
  '{title} 首屏': '{title} screenshot',
  启动中: 'Starting',
  运行中: 'Running',
  已退出: 'Exited',
  启动失败: 'Failed to start',
  '预览 {n} 个': '{n} {n:preview|previews}',
  在线: 'Online',
  离线: 'Offline',
  ' · 服务 {name}': ' · service {name}',
  暂无预览: 'No previews',
  '托管服务 {n} 个': '{n} hosted {n:service|services}',
  ' · 端口 {port}': ' · port {port}',
  停止: 'Stop',
  暂无托管服务: 'No hosted services',
  'Bot 用 service_start 启动的服务由它所在的机器托管，本轮结束后仍在运行；预览 24 小时无人访问会自动关闭。服务停止后预览卡片保留，Bot 重启服务或在卡片上点启动即可恢复。':
    'Services a Bot starts with service_start are hosted by its machine and keep running after the round ends; previews close automatically after 24 hours without visits. When a service stops, its preview card stays; the Bot can restart the service, or click Start on the card to bring it back.',
  '{name} 请求控制': '{name} requests control',
  同意: 'Approve',
  你正在控制: "You're in control",
  交还控制: 'Release control',
  '{name} 正在控制': '{name} is in control',
  仅观看: 'View only',
  接管控制: 'Take over control',
  开始控制: 'Take control',
  收回控制: 'Revoke control',
  取消请求: 'Cancel request',
  请求控制: 'Request control',
  原画: 'Original',
  超清: 'Ultra HD',
  高清: 'HD',
  '自动（{label}）': 'Auto ({label})',
  自动: 'Auto',
  '{label} · 约 {mbps} Mbps': '{label} · ~{mbps} Mbps',
  '自动（{fps} fps）': 'Auto ({fps} fps)',
  '微信开发者工具未登录，请用微信扫码登录': 'WeChat DevTools is signed out. Scan with WeChat to sign in.',
  '等待 Bot 主人登录微信开发者工具': "Waiting for the Bot's owner to sign in to WeChat DevTools",
  微信开发者工具登录二维码: 'WeChat DevTools sign-in QR code',
  服务已停止: 'Service stopped',
  已关闭: 'Closed',
  重新开放: 'Reopen',
  '小程序 · {path}': 'Mini program · {path}',
  '桌面应用 · {name}': 'Desktop app · {name}',
  '服务已停止 · ': 'Service stopped · ',
} satisfies Record<string, string>
