export default {
  '标签页已满（最多 {n} 个），请先关闭一些': 'Too many tabs (max {n}). Close some first.',
  预览已关闭: 'Preview closed',
  关闭标签页: 'Close tab',
  桌面应用: 'Desktop app',
  标签页: 'Tabs',
  关闭其他标签页: 'Close other tabs',
  关闭右侧标签页: 'Close tabs to the right',
  休眠: 'Sleeping',
  '关闭 {title}': 'Close {title}',
  全部标签页: 'All tabs',
  分栏: 'Split',
  专注: 'Focus',
  全屏: 'Full screen',
  工作台: 'Workbench',
  返回聊天: 'Back to chat',
  布局: 'Layout',
  隐藏工作台: 'Hide workbench',
  '改动 · {name}': 'Changes · {name}',
  未提交: 'Uncommitted',
  '已截断，仅显示前 {n} 项': 'Truncated; showing the first {n} {n:item|items}',
  工作区: 'Workspace',
  没有匹配的文件: 'No matching files',
  目录: 'Folders',
  收起目录: 'Hide folders',
  展开目录: 'Show folders',
  搜索文件: 'Search files',
  刷新: 'Refresh',
  显示忽略的: 'Show ignored',
  无法读取工作区文件: "Couldn't read workspace files",
  重试: 'Retry',
  选择左侧的文件查看: 'Pick a file on the left to view it',
  '文件 · {name}': 'Files · {name}',
  自适应: 'Fit',
  进入路径: 'Go to path',
  '回车后从这个路径重新进入；页面内的跳转不会同步到这里':
    "Press Enter to reload from this path; navigation inside the page isn't synced here",
  视口尺寸: 'Viewport size',
  新窗口打开: 'Open in new window',
  '公开链接…': 'Public link…',
  '服务已停止 · 等待 Bot 重新发布': 'Service stopped · waiting for the Bot to republish',
  恢复在线后自动重新加载: 'Reloads automatically once back online',
  小程序: 'Mini program',
  过程: 'Process',
  改动: 'Changes',
  审批记录: 'Approvals',
  '运行过程已过期，仅保留摘要': 'Run details expired; only the summary is kept',
  '{name} 触发': 'Triggered by {name}',
  机器与会话: 'Machine and session',
  模型: 'Model',
  默认: 'Default',
  耗时: 'Duration',
  用量: 'Usage',
  会话: 'Session',
  无法加载运行过程: "Couldn't load run details",
  '{name} · 第 {round} 轮': '{name} · round {round}',
  '{name} · 运行': '{name} · run',
  '无法加载上一轮：{error}': "Couldn't load the previous round: {error}",
  '查看上一轮（还有 {n} 轮）': 'Show previous round ({n} more)',
  'Bot 所在机器离线': "The Bot's machine is offline",
  '停止失败：{error}': 'Failed to stop: {error}',
  '已复制会话 ID': 'Session ID copied',
  '复制会话 ID': 'Copy session ID',
  '接力第 {hop} 跳 · 发起人 {name}': 'Relay hop {hop} · started by {name}',
  '{name} 触发运行': '{name} triggered the run',
  '权限请求：{detail} · {status}': 'Permission request: {detail} · {status}',
  '{name} 停止了运行': '{name} stopped the run',
  '审批与提问记录永久保存；完整运行过程保留 {n} 天，过期后卡片只保留摘要。':
    'Approval and question records are kept forever; full run details are kept for {n} {n:day|days}, after which cards keep only a summary.',
} satisfies Record<string, string>
